const INTRO_MAP = {
    "zh-TW": {
        "Alice": "卡片占卜專家\n你的未來我來負責！\n提供預知未來卡片占卜的親切幽靈。即使只是為了打發時間而占卜，最終也可能只會確認到不幸的運勢，讓人百般後悔。",
        "Allet": "老么下士\n辦理戶籍遷入！\n莫納蒂姆鎮壓隊中最年輕的下士。不管康娜下達什麼命令，絕對使命必達的熱情軍人。要說缺點的話，就是不聽從比康娜更高階的艾琳娜及艾蜜莉雅的話。",
        "Amelia": "公認的最佳秘書\n我是助手艾蜜莉雅。呼喚我有什麼事嗎？\n精靈城市莫納蒂姆的市長秘書。代替艾琳娜管理莫納蒂姆的工作狂。經常可以看到她對「艾琳娜」有著極端的執著，這讓所有看到的人都覺得恐怖。",
        "Ashur": "艾利亞斯麵包王\n妖精界最強大的魔法師艾舒爾出場！\n妖精王國最好吃的麵包店老闆，也是最低等魔法學校的校長。如果不想聽到她自卑感爆發的情感宣洩，最好避免提及麵包店。",
        "Aya": "萬年雪的賢者\n你來是有什麼煩惱嗎？我都會聽你說的。\n被稱為萬年雪之賢者的魔女。在艾利亞斯中是少數能進行深層思考的居民。許多居民都會向綾請求建議。但有時會不自覺地說出超出底線的話。",
        "Belita": "最高階魔女\n根部的守護者、魔女女王。\n魔女中至高無上的女王。不僅是在魔女中，在整個艾利亞斯看來，她是唯一配得上「女王」稱號的存在。她對艾利亞斯的領袖們具有很大的啟發作用。",
        "Beni": "反對獸糧黨的力量\n費力的事就交給我！\n總是悠閒，總是吃貨的熊獸人。性格溫和，這也是她經常被利用的缺點。負責反對獸糧黨中唯一的基層職位。",
        "BigWood": "最勇敢的魔靈\n保護大自然……\n看起來蠻可靠的樹之靈。但當真正接近並交談時，她偶爾會說出讓人毛骨悚然的話。大概沒有什麼險惡的意圖吧，應該。",
        "Blanchet": "舞台上的藍玫瑰\n希望我的演技有完整的傳達出去。\n在莫納蒂姆做演員的藍玫瑰之靈。身為魔靈的她能夠在莫納蒂姆堅強的生活下來，很大的原因是因為對表演的熱情和自信心。她希望有一天可以克服自己情感表達不足的弱點，成為備受愛戴的演員。",
        "Butter": "熱愛朋友\n我們一起玩吧！要玩什麼遊戲？\n永遠活潑開朗的獸人，總是努力結交朋友。據說沒有人見過奶油生氣的樣子……也許總有一天會看到吧？",
        "Canna": "遊樂場霸王\n遵命！\n精靈城市莫納蒂姆的鎮壓隊隊長。在來到艾利亞斯之前，她似乎是一位地位相當高的軍人。對上級的命令絕對服從。",
        "Carren": "沒人看的戲精\n那是當然的啦！\n卡蓮是一個堅持不料理，直接食用原型材料的「原型生食者」。曾經引領生食主義的潮流，但後來被發現只是一個喜歡加調味料食用的偽君子而因此沒落。",
        "Chloe": "玩偶沙袋權威\n我是庫洛艾，它是塞巴斯蒂安。不要搞混了。\n說到時尚，絕對不輸給任何人的裁縫師妖精。對於玩偶「塞巴斯蒂安」瘋狂著迷。雖然個性冷漠又怕生，但對於自己工作相關的事絕對有始有終。",
        "Chopi": "熱情新手\n無論如何我要變強，獲得認可！\n剛開始執行修練的年幼獸人。自己視為榜樣的對象們好像都有點問題，但卻渾然不知的樣子。這天真又虔誠的信念不覺得像是在造神嗎？",
        "Cuee": "小黃瓜奥義\n喂喂，你是問我有沒有在等你嗎？\n路易是一位喜歡在食物中加入小黃瓜的「小黃瓜派」妖精。她努力將喜愛度差異兩極化的小黃瓜變成妖精社會的主食，但似乎有點勉強。",
        "Diana": "歲月賦予的智慧\n睜隻眼閉隻眼也是有限度的。\n獸人們信從的賢明長者。有傳聞說，蒂亞娜曾有過一段血氣方剛的過去。",
        "Ed": "永恆的做夢者\n和我一起永遠做夢吧。\n在生命維持裝置「娜塔」中做夢的精靈。她把所見、所聽、所感的一切都視為夢境，而非現實。伊德與娜塔透過腦波交流，分享彼此的溫暖，並一起適應這個陌生的艾利亞斯。",
        "Elena": "精靈的實質領袖\n有需要的話，當然也要立合約。\n精靈城市莫納蒂姆的市長。對自己的研究和發明充滿自豪的機械魔法工程師。表面上試圖與其他種族保持良好關係，但……精靈通常會為了目的說謊，所以很難完全信任。",
        "Epica": "艾利亞斯的吟遊詩人\n我可以演唱你的故事嗎？\n艾利亞斯的獸人流浪者，也是吟遊詩人。總是以活潑的模樣訴說著故事，喜歡戲劇性的內容。似乎尋覓著最新故事和「最終的主角」而流浪，並在教團中找到立足之地。",
        "Erpin": "妖精女王\n艾利亞斯的守護者，登場！\n妖精的女王。對甜點無法抗拒。儘管有時看起來可憐，而且確實有很多不足，但她還是在努力。無論她多麼不守規矩，總有讓人無法討厭她的地方。",
        "Espi": "偷看夢境專家\n你會做有趣的夢嗎？\n無法做夢的夢之幽靈。似乎總是竊取別人的夢來自我滿足。曾多次潛入沉睡的居民家中，因此名聲不太好。",
        "Festa": "艾利亞斯的最佳搖滾樂手\n我會用我的音樂戰勝世界！\n拒絕一切束縛自己的規則和體制，是歌頌自由的藝術家。自稱是「自由鬥士」，但……看起來不過是單軌電車站的流浪漢。她是否真能理解自由的意義也是個疑問。",
        "Fricle": "貝麗塔的輔佐官\n滅亡的徵兆～芙莉可！\n輔佐魔女女王的魔女王國第二把交椅。總是在制定「某個計劃」，並對此感到非常自豪。為了展開自己含帶惡意的理想，她不在乎周圍的目光。",
        "Gabia": "最安靜的魔靈\n嗯？！\n沉默寡言的地之靈，似乎不是因為害羞。因為聲音太小，別人可能不知道她在說話。有些魔靈似乎能很好地理解加薇雅的話。",
        "Haley": "自稱精靈先鋒隊軍官\n你願不願意和我一起邁向和平的道路？\n堅信自己還在職的精靈軍退役軍官。地球侵略時期留下的PTSD，使她以為自己現在待在同盟國「艾利亞斯」。今天她也持續在妄想中，為了守護世界和平而努力著。",
        "Hilde": "萬年住院醫師\n呵呵，準備好接受診療了嗎？\n莫納蒂姆大學醫院的資深住院醫師。曾經很討厭那種背咒語就能馬上讓病痊癒的「魔法」，但來到艾利亞斯後放下固執，正在研究艾利亞斯式醫學。她溫柔親切，尤其在精神科治療方面很受歡迎。",
        "Ifrit": "老古板的魔靈\n火熱地大幹一場！\n不管有沒有理由，都先發脾氣再說的專家。據說她會私下選擇發脾氣的對象，是個擅長控制憤怒的專家。",
        "Jade": "不要嘲笑我耳根子軟\n我會收集一切、完成所有知識的收藏！\n視知識為寶藏的龍族，玉龍族。對知識貪婪過度，以至於不願教導他人，以免知識傳遍開來。雖然是龍族，卻沒有翅膀……不知道背後有什麼故事？",
        "Jubee": "蜂蜜產量第一\n我不是蟲子，我是蜜蜂嗡。\n在艾利亞斯的森林閒晃的話，常常可以看到的……野獸？昆蟲？不，是魔靈。在森林裡散步時很可能會遇到茱蜜，最好別太煩她。",
        "Kidian": "自願邊緣人\n待在黑暗的地方也不壞。\n龍族中的自願邊緣人，黑曜石龍族。因為太習慣獨自一人，過度害羞，認為自己無足輕重，這常引起周圍人的同情。",
        "Kommy": "獸人讀書王\n柯米現在可以睡了吧？\n外表呆萌、實際上卻出奇地聰明的獸人。問題是，她也隱約有些傻氣？好像有很大的野心……希望不是什麼危險的事。",
        "Kyarot": "手工栽培的農婦\n要來我的花園玩嗎？\n卡洛特是個能把任何東西都種得很大的妖精園丁。她在世界樹周圍建了一座花園，種植巨大的甘蔗。雖然她曾經蔑視提供糖分的精靈，但現在也許改變想法了？",
        "Lazy": "工作精神\n你要派我去工作嗎？\n雖然是莫納蒂姆市的IT管理部門職員。但因為過去曾展示過自己許多過人的長處，因此被任命於各種大小事中，成為一個苦命的精靈。",
        "Leets": "冶煉萬次的鋼鐵\n我能夠成為比得上強者的……挑戰者吧？\n透過無數次鍛鍊，重生為鋼鐵的龍族。過去個性果斷、大膽，但出於某種原因變得膽小且優柔寡斷。時不時舊有的個性會浮現，或許是有存在某種感應。",
        "Levi": "打工專家\n咦、咦？？找我有什麼事嗎？\n努力工作、不停工作、持續工作的魔女。魔女們稱萊薇為小妹，並讓她做各種雜務。總是看起來很疲倦。",
        "MaestroMK2": "最高規格機器人\n大師2號，完成啟動準備。\n看似沒有靈魂的機器人。有時候，它的行為讓人覺得它或許有靈魂。要將大師2號當作人格體對待抑或是物品，取決於對方的態度。",
        "Mago": "熱愛和平的獸人\n相親相愛地玩在一起吧。\n喜歡保護和照顧小動物朋友們的友善獸人。馬爾的小朋友們也因為非常聽從馬爾的話而聞名。",
        "Maison": "天天都是安息日\n這裡就是新家嗎？\n安息定居的幽靈。總是維持著平靜的情緒，對自己所在或所去的地方都視如家一般的奇特個性。不太清楚這樣的個性是代表什麼意義。",
        "Marie": "可處理爆炸物\n有東西擋在前面就爽快的炸掉！\n妖精王國的探險家。雖然她從事尋找遺物和寶物的工作，但她似乎對保存它們沒有太大的興趣。總是先炸了再說。似乎曾經做過一些心虛的事情。",
        "Mayo": "最佳的贓物收藏家\n今天又增加收藏品了。\n精通收集某種東西的妖精。只要是特殊物品，就會先收集起來，甚至擁有自己的收藏店。據說將物品託付給瑪約後就很難再拿回來了。",
        "Meluna": "版稅收入第一\n梅露娜～哈密瓜之靈～為我唱一首歌吧～\n跟寵物「馬斯克」同行的哈密瓜之靈。乍看之下很平凡，但據說擁有驚人的財力。最好在她面前保持好形象。",
        "Momo": "總有一天會是最強忍者\n隨時都很歡迎簡單又輕鬆的委託！\n夢想成為艾利亞斯最強忍者的獸人。她發揮實力幫許多居民解決問題，卻也常常犯奇怪的失誤。如果想委託桃桃辦事，建議準備花蜜取代獸糧。",
        "Mynx": "脫線老師\n不是這樣做的啦！\n有著豐富經驗，負責教育年幼獸人們的獸人。但經驗豐富並不代表會教學。米雪自己都不知道該教些什麼時，獸人學生們反而更喜歡自行學習。",
        "Naia": "社交能力我最強\n世界的基本元素水之靈奈雅登場～！\n用輕鬆的惡作劇點亮周圍氣氛的魔靈。可以說是艾利亞斯的人氣王。有點不正經，有時會讓周圍人感到尷尬。",
        "Ner": "最高階祭司\n為了世界樹，我願意做任何事。\n表面上帶著慈愛的微笑，背後隱藏著什麼的世界樹教團的祭司長。有著完美主義，對周圍的人要求嚴格。只要是與世界樹和教團相關的事，她總是不遺餘力。",
        "Patula": "地獄大廚\n在廚房要正經！\n妖精王國麵包街的烹飪實習生。她在以艾舒爾為首的麵包店主人們那裡接受烹飪指導，夢想著有一天也能成為最頂尖的糕點師。個性似乎相當敏感，不太討人喜歡。",
        "Picora": "艾利亞斯的時尚達人\n總有一天，我會讓大家都羨慕我！\n熱愛大膽造型的魔女。沉浸在地面上外放且華麗的氛圍後，而逃離冷漠的魔女王國並現居在森林中。據說她夢想著有一天可以受到所有魔女的認可，成為地面上的造型師網紅。",
        "Posher": "藥水製作匠人\n呵呵，啾啾，不要剩下，連最後一滴都要喝乾淨。\n俗稱賣藥女巫。她親自製作藥水，在自己的藥水店販賣。據說珀榭製作的藥水效果驚人，但必然伴隨著嚴重的副作用。",
        "RenewaAwaken": "多次元流浪精靈\n為了迎接明天，我們可以一起渡過此刻嗎？\n最近某處出現了一個在妖精王國劇場打工並擔任售票員的精靈。雖然因為工作而感到疲憊，偶爾也會胡言亂語，但基本上對任何人都表現出親切的樣子。",
        "Rim": "冷笑話權威\n我是琳……秩序的幽靈。\n守護艾利亞斯平衡的幽靈。一旦有人闖禍，她總能突然出現，成為他人的力量。在幽靈中，她擁有最獨特的幽默感。",
        "Risty": "現實生活駭客\n哼！沒有我攻略不了的遊戲。\n莫納蒂姆的無業者、職業玩家，自稱駭客。她原本是個無所事事的無業遊民，但在一連串的事件後，獲得了現實破解的能力，並逐漸恢復了自信。從她對精靈特有的背叛抱持懷疑態度來看，她的本性其實相對善良。",
        "Rohne": "最佳間諜？\n親切的鄰居間諜，洛涅～！\n看起來糊塗的精靈卻是頂尖間諜。有時看著她，都很懷疑到底是不是頂尖的。不管怎麼看似乎都只是個普通間諜……因為本性不壞，無論在哪都能融入。",
        "Rude": "用肌肉解決問題\n我是值得追隨的強者嗎？\n龍族的官方萬年老二，紅寶石龍族。據說，從過去到現在，能打敗路德的龍族寥寥可數。如果不喜歡運動，就不容易和他們親近。",
        "Rufo": "反對獸糧黨知識王\n需要我的妙計嗎？\n充滿傲氣的獸人。雖然行為總是讓人討厭，但看她周圍有不少朋友，似乎她的人際關係還不錯。她擔任著反對獸糧黨的首腦。",
        "Sari": "反應大師\n先幫我起個頭。\n無法知道莎莉是怎麼樣的幽靈。她很喜歡附和其他幽靈們的對話及動作，這會是提示嗎？",
        "Selline": "挑釁女王\n剛才那個表情非常好。\n以取笑並使他人生氣為樂的幽靈。她有著一個厲害的技巧，那就是說話時乍聽之下溫和友善，但會越聽越讓人氣憤。除了自己之外，包含同種的幽靈都是她的戲謔對象，但據說最佳戲謔對象中的第一名是精靈無誤。",
        "Shady": "惡作劇專家\n要怎麼惡整你呢？嘻嘻！\n幽靈們爭相模仿的對象。沒有幽靈能像謝蒂一樣搞出那樣大規模的惡作劇。她認為世界末日將是終極的惡作劇？",
        "Shoupan": "極限速度狂人\n只要有超霸雷霆，我就能去任何地方！\n以極速橫跨艾利亞斯的快遞員。駕駛著超霸雷霆，四處奔馳，樂在其中。她對快速交貨充滿熱情，但對物品的安全性毫不關心。",
        "Silphir": "自尊心當飯吃\n龍族的第二把交椅，希菲爾大人！\n一心想攀上顛峰的藍寶石龍族。總是覬覦更高的地位。看似魯蛇，實際上已位居很高的地位。除了對地位的執著外，幾乎沒有什麼缺點的使者。",
        "Sist": "詐欺犯新星\n要買些什麼嗎？請儘管說，嘿嘿。\n任何東西都能買賣的商販龍族，紫水晶龍族。似乎有個遠大的目標，但她藏得很深，所以知道的人不多。",
        "Snorky": "地下黑幫\n有本事就來抓我啊。\n曾風光一時的黑幫頭目流氓魔女。如今她跟隨著教主，並自封為教主的保鏢。斯諾奇究竟是真的信服教主呢？還是在打什麼鬼主意，只有她才知道了。",
        "Speaki": "入戲太深的專家幽靈\n我是世界樹的祭司寧琉！嗯？斯皮奇是誰？\n無腦的模仿幽靈。對模仿特定對象非常認真。看起來似乎沒有壞意，但似乎不太考慮對方的感受。",
        "Sylla": "最佳名射手\n千萬不要小看尊貴魔靈首領。\n艾利亞斯最酷的風之靈。有時候可能感覺有點無情或有壓迫感。被視為魔靈中的大姐大。",
        "Taida": "地縛靈第1名\n咦？我、我沒有在玩！\n莫納蒂姆市政廳的守衛。擅長躲避上級並愛偷懶的精靈。專長是避開艾蜜莉雅的視線偷偷上網，對於管理自己的精靈瀏覽歷史紀錄非常嚴謹。",
        "Ui": "正向力量\n我會讓大家只想到美好的事情！\n總是和摯友青蛙耶魯在一起的毛毛雨之靈。總是以正向的態度看待世界，任何困難或不幸對羽伊來說都只是小事。即使在灰濛濛的天空下，有羽伊的地方都能感受到莫名明亮的氛圍。",
        "Velvet": "肌力強化魔法專家\n嗯～你看起來蠻厲害呢？\n追求力量的魔女中最不擇手段的一個……社交關係中需要一點矯情，但她似乎完全不在乎。由於強烈的權力慾，經常製造麻煩，是個闖禍精。",
        "Veroo": "無添加濾鏡\n你全身都是弱點耶？\n有缺陷的幽靈。貝魯是以詆毀他人而聞名的幽靈。她有一個習慣，就是毫不顧忌地挑出別人的缺點並加以貶低。",
        "Vivi": "龍族聖骨貴族\n真有勇氣，我就暫且陪你玩玩吧。\n曾是位居在達雅之後，排名第二的銀龍族。因為患有強迫症，總是努力將周圍打掃乾淨。但經常會因為慢性全身疼痛而打噴嚏。或許感到不舒服的使者們是因為跟薇薇接觸過後而被傳染的？",
        "xXionx": "黑暗魔彈射手\n我是從光明和黑暗的邊界回來的人！\n艾利亞斯的暗之光，自詡為「魔彈射手」。沉浸在自己的世界，無法自拔的幽靈。乍看難以相處，但只要迎合她喜歡的黑暗及莊嚴取向，似乎很容易就能成為朋友。",
        "Yomi": "故事中的向月花\n當太陽沉睡時，月亮便會照亮世界。\n在月光皎潔的夜晚，我偶然遇見了一位月亮祭司。據寧琉所說，追隨月亮的祭司乃古老傳說中的存在……看她時不時來教團找我，表現出追隨我的樣子，感覺她就是個溫柔善良的傢伙。",
        "Yumimi": "懶散獵人\n啊～草的味道好好聞～\n滿足自身現況與處境的自給自足型獸人。據說很少去村子，主要都在森林裡生活。劉美美空置的房子有時會被調皮的獸人們當作遊樂場使用。"
    },
    "ja": {
        "Alice": "カード占い専門\nあなたの未来を預かってあげるわ!\n予知能力が込められたカードで占いをしてくれる愛想の良い幽霊。退屈しのぎにカード占いを頼むと、運勢は凶だけが出て、後悔することになる。",
        "Allet": "末っ子伍長\n転入届を提出します!\nモナティアム鎮圧班で一番若い伍長。カンナの命令なら何でもする熱血軍人。カンナよりも上のエレナやアメリアの言うことを聞かないのが強いて言えば彼女の短所。",
        "Amelia": "自他共に認める最高の秘書\n助手のアメリアです。何のご用でしょうか?\nエルフの街モナティアムの市長の秘書。エレナの代わりにモナティアムを運営するワーカホリック。しばしば「エレナ」に度を越して執着する姿を見せる……それを見た者はみな、口をそろえて怖いと言う。",
        "Ashur": "エーリアスの製パン王\n最強の妖精、大魔法使いエシュールが来たわ!\n妖精王国で最高のベーカリーの店主であり、最低の魔法学校の校長。熱い感情の吐露を聞きたくなければ、ベーカリーの話は避けた方が良い。",
        "Aya": "万年雪の賢者\n悩みでもあるのかしら?何でも聞いてあげるわ。\n万年雪の賢者と呼ばれる魔女。エーリアスでは数少なく思慮深い住民。そんなアヤにあれこれ助言を求める住民は多い。しかし際どい言葉を時々無意識に口にすることもある。",
        "Belita": "最高位魔女\n根の守護者、魔女の女王である。\n魔女たちの最高権威者である女王。魔界だけでなく、エーリアス全体で見ても、「女王」という表現が似合う唯一の存在。エーリアスの指導者たちの手本となっている。",
        "Beni": "反アニマル缶戦線の力\n力仕事なら任せろ!\nいつもゆったりとしていて、食いしん坊のクマの獣人。性格が丸いので、あちこちで利用されてしまう。反アニマル缶戦線の唯一の下っ端隊員を務めている。",
        "BigWood": "最も勇敢な精霊\n自然を守るの……\n頼もしそうに見える木の精霊。しかし近づいて話してみると、なぜかゾッとするようなことを言う。何か陰険な企みがあるわけではないだろう。たぶん。",
        "Blanchet": "舞台の上の青い薔薇\n私の演技がきちんと伝わりますように。\nモナティアムで女優をしている青い薔薇の精霊。精霊である彼女がモナティアムで元気でしっかりと生活できるのは、演技に対する情熱と自負心のおかげ。いつか弱点である感情表現の不足を克服して、多くの人に愛される女優になりたいと思っている。",
        "Butter": "友達大好き\n一緒に遊びましょ! 何して遊びましょうか?\n明るく快活な獣人。いつも友達を作ろうと努力する。……誰もバターが怒っている姿を見たことがないと言うが、見られるのはいつだろうか?",
        "Canna": "ゲームセンターの覇王\nはい、了解であります!\nエルフの街モナティアムの鎮圧班隊長。エーリアスに来る前は、かなり階級の高い軍人だったようだ。上官の命令なら、何でも従う。",
        "Carren": "没落した目立ちたがり屋\nアメーニンジング!\nカレンは食材をそのまま食べなければならないという「根本生食家」。一時生食トレンドをリードしたが、ドレッシングをかけて食べる偽善者だということが明らかになり、没落した。",
        "Chloe": "ぬいぐるみサンドバックの権威\nあたいはクロエ、こっちはセバスチャンよ。間違えないでね。\nファッションのことなら誰にも負けない仕立て屋の妖精。ぬいぐるみの「セバスチャン」に恐ろしい執着を持っている。気難しい性格で人見知りをするが、自分の仕事に関連することには徹底している。",
        "Chopi": "情熱の青二才\nがんばって強くなって認めてもらうよ!\n鍛鍊を始めたばかりの幼い獣人。憧れの対象が少しズレているが、本人はそれをよくわかっていないようだ。無垢な夢への信仰が英雄を作るのではないだろうか?",
        "Cuee": "エクスキュウリバー\nキュウキュウリ如律令!\nキュウイは食べ物にキュウリを混ぜて食べる「キュウリ派」妖精。好き嫌いが分かれるキュウリを妖精社会の主流にするために努力しているが、おそらく無理。",
        "Diana": "亀の甲より年の功\n目をつぶってあげるのにも、限界がありますよ。\n獣人たちが信頼して従う賢明な長老。住民の間では、ディアナはかなり血気盛んな過去を生きてきたという噂がある。",
        "Ed": "エターナルドリーマー\n私と一緒に永遠に夢を見るのよ。\n生命維持装置「ナタ」の中で夢を見るエルフ。自分が見て、聞いて、感じるすべてを現実ではなく夢だと思っている。ナタと電脳信号で会話し、互いの温かさを分かち合いながら、共に馴染みのないエーリアスに適応している。",
        "Elena": "エルフの真のリーダー\n必要なら正式な契約も結ぼうか。\nエルフの街モナティアムの市長。自分の研究と発明品に大きな自信を持っている機械魔法工学者。表面的には他の種族と良好な関係を維持しようとしているが……エルフは通常、目的のために嘘をつくので、完全に信用するのは難しい。",
        "Epica": "エーリアスの吟遊詩人\nあなたの物語を歌わせていただいてもよろしいでしょうか?\nエーリアスの獣人放浪者であり、吟遊詩人。いつも活発な様子で物語を語るように話し、劇的な状況を好む。新しい物語と「究極の主人公」を探し求めて放浪していたが、教団に落ち着くことにしたようだ。",
        "Erpin": "妖精の女王\nエーリアスの守護者、登場!\n妖精たちの女王。甘いデザートには目がない。情けなく見える時もあり、足りないところが多いのは事実だが、自分なりに努力している。どんなに生意気な行動をしても憎めないところがある。",
        "Espi": "夢覗きスペシャリスト\n面白い夢を見せてくれるの?\n夢を見られない夢の幽霊。いつも他人の夢を盗み見ることで、間接的に満足しているようだ。眠っている住民の家にこっそり侵入することが多く、評判が良くない。",
        "Festa": "エーリアス最高のロッカー\nおいらのビートで世界を勝たせてやんよ!\nルールや統制など、自分を束縛するものを全て拒否し、自由を謳歌するアーティスト。「自由の闘士」と自称するが……ただのモノレール駅のホームレスと見ても差し支えない。自由の意味を正しく理解していないかもしれない。",
        "Fricle": "ベリータの補佐役\n破滅の前触れ~ フリックル様だ!\n魔女の女王を補佐する魔女の王国の2番手。常に「ある計画」を立てており、そのような自分に対する自負心が強い。自分の恐ろしい理想を広げるためなら、周囲の視線など全く気にしない。",
        "Gabia": "最も静かな精霊\n(「うん?」という呟き)\n口数の少ない大地の精霊。臆病者というわけではなく、声が小さくて、話しているのかどうかもわからないだけ。一部の精霊はガヴィアの言葉をよく理解しているようだ。",
        "Haley": "自称エルフ前衛隊将校\n平和への歩み、私と共に歩むと約束しないか?\n自分はまだ現役だと信じているエルフ軍の退役将校。地球侵略時代のPTSDで現在、自分が同盟国である「エーリアースー」にいると妄想している。今日も想像の中の世界で平和のために頑張っている。",
        "Hilde": "万年研修医\nフフッ、診察を受ける準備はできましたか?\nモナティアム大学病院の万年研修医。呪文を唱えると病気が治る「魔法」を嫌っていたが、エーリアスに来た以上、こだわりを捨ててエーリアス式の医学を研究中。優しくて親切なので、メンタルケアがとても人気。",
        "Ifrit": "お局精霊\nいっちょ、たきつけてやろうぜ!\n理由の有無に関わらず、とにかく怒る専門家。密かに対象を選んで怒り、怒り加減まで調節できるという。",
        "Jade": "カモって言うな\n私のものだから、私だけが見られる知識のコレクション!\n知識を宝物のように大切にする竜族、翡翠の竜族。知識に対して独占欲が強すぎて、他人に教えて知識が広まることを嫌う。竜族なのに翼がないのは……何か事情があったのだろうか?",
        "Jubee": "蜜生産量1位\n虫じゃないんだビー。ミツバチだビー。\nエーリアスの森を歩いていると、よく見かける……? 昆虫? いや、精霊。庭を歩いているとシュビーと頻繁に遭遇するが、あまり邪魔をしない方が良い。",
        "Kidian": "自発的な異分子\n暗い所にいるのも悪くないよ。\n種族から自発的に離れる一匹狼、黒曜石の竜族。一人でいることに慣れて、必要以上に人見知りをする。自信がないところが見られると、周囲の人が同情してくれる。",
        "Kommy": "獣人読書王\nコミーはもう寝てもいいかにゃ?\nぼんやりとした見た目とは裏腹に、意外と賢い人。問題は、わざと惚けることがある点かも? 何か大きな野望を抱いている様子……危険なものでなければいいのだが。",
        "Kyarot": "手作業農婦\n私の庭に遊びに来ない?\n何でも大きく育てることができる妖精の園芸家。世界樹の周りに庭を作って巨大なサトウキビを育てている。砂糖の供給者であるエルフたちを見下す一面があったが、今は変わったかも?",
        "Lazy": "働く魂\n仕事をさせようとしていますか?\nモナティアム市のIT管理班の職員。過去に自分のいろんな才能を発揮してしまったため、仕事の重要性と関係なく様々なことに駆り出され、連れて行かれる悲運のエルフ。",
        "Leets": "数万回鍛えた鋼鉄\n強者に相応しい挑戦者に……なれるでしょうか?\n数え切れないほどの鍛錬を経て、鋼鉄のように生まれ変わった竜族。勇猛果敢な性格だったが、何らかの理由で臆病で優柔不断な性格になってしまった。時々昔の性格が顔に出るのを見ると、何かトリガーが存在するのかもしれない。",
        "Levi": "アルバイト専門家\nは、はい?? なんで呼ばれたんだろう?\n一生懸命働き、まだ働き、ずっと働き、次々と働く魔女。魔女たちはレヴィを末っ子と呼び、あらゆる雑用を任せっぱなし。いつも疲れている様子。",
        "MaestroMK2": "最先端ロボット\nマエストロMK2、作動準備完了しました。\n魂がなさそうに見えるロボット。時折、実は魂があると思わせる行動をする。マエストロMK2を人間として扱うか、物として扱うかは相手によって異なる。",
        "Mago": "平和を愛する獣人\nみんなで仲良く遊ぶのよ。\n小さな動物の友達を守り、世話をするのが好きな優しい獣人。マーゴの友達はみんなマーゴに従うことで有名。",
        "Maison": "毎日が安息日\nここが新しい家なのかな?\n安息の幽霊。いつも落ち着いた感情を維持し、自分がいる場所、行く場所を全て家のように思おうとする奇妙な性格。そんな性格にどんな意味があるのかはよくわからない。",
        "Marie": "爆発物取扱可能\n道をふさぐ物があればスッキリ吹っ飛ばしてしまいましょう!\n妖精王国の探検家。遺物や宝物を探す仕事をしているが、保存にはあまり関心がない。とりあえず何でもかんでも掘り出してしまう。過去に何か後ろめたいことをしたようだ。",
        "Mayo": "最高の盗品コレクター\n今日もコレクションが増えたっす。\n何かを収集することに長けた妖精。変わった物なら、とりあえず収集してしまう。自分の骨董屋まで持っている。マヨに預けた盗品は、返してもらうのは難しいという。",
        "Meluna": "印税収入1位\nメロナー、メロンの精霊~ 私に歌を歌ってください〜\nペットの「マスク」と一緒にいるメロンの精霊。一見普通だが、なぜか莫大な財産を持っているという噂がある。早めにコネを作った方が良さそう。",
        "Momo": "いつかは最強のニンジャ\n簡単で楽な依頼はいつでも歓迎です!\nエーリアス最高のニンジャを夢見る獣人。実力を発揮して住民たちの依頼を解決しているが、ヘマをする時も多い。モモに依頼したいならアニマル缶の代わりに花蜜を準備しよう。",
        "Mynx": "残念な先生\nそうじゃないから!\n幼い獣人の教育を担当する、それなりに経験豊富な獣人。しかし、経験が豊富なことと教えることは別物。ミンス自身も何を教えればいいのかわからない時が多く、生徒の獣人たちは一人で学ぶことを好む。",
        "Naia": "コミュ力モンスター\n世界の必須要素水の精霊ナイア登場~!\n軽い悪戯で周囲を明るくしてくれるムードメーカーの精霊。エーリアスのパリピとも言えるだろう。少し真面目さに欠けるため、周囲を困惑させることもある。",
        "Ner": "最高位司祭\n世界樹のためなら、なんでもいたします。\n慈愛に満ちた笑顔の背後に何かを隠している世界樹教団の司祭。完璧主義で周囲に厳しく接するタイプ。世界樹と教団に関連することなら、毎回力を惜しまない。",
        "Patula": "地獄の料理長\nキッチンでは真剣に!\n妖精王国ベイカー通りの料理見習い。エシュールをはじめとするベーカリーの店主たちから料理の指導を受けながら、いつか最高のパティシエになることを夢見ている。性格はかなり敏感で、あまり好かれていないようだ。",
        "Picora": "エーリアスのファッショニスタ\nいつか、みんなの羨望の的になってやる!\nやりすぎコーデを愛する魔女。地上界の明るく華やかな雰囲気にすっかりハマった後、固くてつまらない魔女の王国から逃げ出して森で暮らしている。いつか全ての魔女に認められる地上界のファッションインフルエンサーになるのが夢という。",
        "Posher": "ポーション製作職人\nふふふ。ぐぐーっと、残さず最後の一滴まで飲み干してね。\nいわゆる薬屋の魔女。自らポーションを調合して、自分のポーション店で販売している。ポーシャーが作ったポーションは効果が絶大だが、その分大きな副作用が伴うという。",
        "RenewaAwaken": "多次元放浪エルフ\n明日を迎えるために今を一緒にいてもらえませんか?\n最近どこからともなく現れて、妖精王国の劇場でチケット販売のアルバイトをしているエルフ。仕事の疲れからか、時々ブツブツ独り言を言っているが、基本的には誰にでも親切。",
        "Rim": "スベりの権威\n私はリム……秩序の幽霊。\nエーリアスの均衡を守る幽霊。大きな困難に陥る人がいると、どこからともなく現れて力になってくれる。幽霊たちの中で最も独特なユーモアセンスを持っている。",
        "Risty": "リアルライフハッカー\nフッ! 私に攻略できないゲームはないってこと。\nモナティアムのニートであり、プロゲーマーであり、自称ハッカー。無気力なニートだったが、一連の事件の後、現実ハッキング能力を得て自信回復中だ。エルフ特有の裏切りに懐疑的なのを見ると、本性は意外にも善良そうだ。",
        "Rohne": "最高のスパイ?\n親切な隣人のスパイ、ローネです〜!\n少し子供っぽく見えるエルフのスパイのエース。時々本当にエースの名に相応しい実力を持っているのかが疑わしくなる。どう見ても下っ端スパイ以下のように見えるが……性格は悪くないため、どこでもうまく溶け込んでいる。",
        "Rude": "筋肉で勝負する\nオレが従うに足る強者なのか?\n公式的には竜族の序列2位、ルビーの竜族。過去から現在まで、ルードを倒した竜族は数えるほどしかいない。運動が好きでなければ、仲良くなるのは難しい。",
        "Rufo": "反アニマル缶戦線の知識王\nあたいの計略が必要かい?\nうぬぼれ屋の獣人。いつも憎たらしい行動をするが、親しい友達がいるところを見ると、周囲との関係はそんなに悪くない。反アニマル缶戦線の頭脳担当。",
        "Sari": "リアクション職人\nまずテーマを決めよう。\nサリーが何の幽霊なのかはわからない。他の幽霊たちの会話や行動に相づちを打つことに執着しているが、これがヒントだろうか?",
        "Selline": "挑発の女王\nさっきの表情はとてもよかったわ。\n他人をからかって怒らせるのが趣味の幽霊。一見すると穏やかな口調だが、聞けば聞くほど腹が立つという、とてつもない技術を持っている。幽霊だけでなく、自分以外の全員が彼女の獲物。一番の大物はやはりエルフ。",
        "Shady": "悪戯専門\nどうやって遊んであげようかしら? ヒヒ!\n幽霊たちの憧れのロールモデル。シェイディほどスケールの大きな悪戯をできる幽霊はいない。世界が滅びるのが究極の悪戯なのか?",
        "Shoupan": "エクストリームスピードスター\nシュパボルトと一緒なら、どこにでも行けるよ!\nエーリアスを駆け抜けるスピード狂の配達員。シュパボルトに乗ってあちこちを走り回ることを楽しむ。迅速に配達することには使命感を持っているが、荷物の安全性については気を配っていない。",
        "Silphir": "プライドで腹を満たす\n竜族の2番手、シルフィール様よ!\nトップの座を狙って、常に序列上位者に挑戦することに執着するサファイアの竜族。噛ませ犬のようで、かわいそうに見えるが、実は竜族内で非常に高い序列にいる。序列に対する執着さえなければ、特に欠点のない使徒。",
        "Sist": "詐欺師の逸材\n何かご入用ですか? なんでも言ってくださいな、へへっ。\n何でも売り買いして商売をするアメジストの竜族。何か壮大な目標があるようだが、しっかりと隠しているので、それについて知っている者は極めて少ない。",
        "Snorky": "アンダーグラウンドギャングスター\nどれ、一丁やってみるか!?\n過去、かなりヤンチャなギャングのボスだったゴロツキ魔女。現在は教主をボスとして従属し、自らボディガードを名乗っている。スノーキーが本当に教主を認めたのか、クーデターを夢見ているのかは彼女にしか分からない。",
        "Speaki": "なりきり専門幽霊\n世界樹の司祭、ネルです! はい? スピッキーって誰ですか?\n何も考えずに真似をする幽霊。特定の対象を真似ることに熱中する。悪意があるようには見えないが……対象の気持ちは考慮していないようだ。",
        "Sylla": "最高の名射手\n上位精霊の長をなめるな。\nエーリアスで最もクールに振る舞う風の精霊。時々少し冷淡だったり、高圧的に感じられることもある。精霊たちの姉御のような存在でもある。",
        "Taida": "サボりの第一人者\nあっ? いや、遊んでたわけではないです!\nモナティアム市庁舎の警備員。上司を避けてサボることに長けたエルフ。特技はアメリアの目を盗んでネットサーフィンをすることで、自身のエルフネット閲覧記録の管理を徹底している。",
        "Ui": "ポジティブの力\nみんなが良いことだけを考えるようにしてあげるね!\n親友であるカエルのエルと一緒にいる雨の精霊。いつも世界を肯定的な態度で見つめ、どんな苦難や不幸もウイにとっては取るに足りない。どんよりとした曇り空の下でも、ウイがいる場所はなぜか明るい雰囲気を感じる。",
        "Velvet": "筋力強化魔法専門\nふ~ん。あんた、強そうだね?\n力を追い求める魔女の中で……最も手段を選ばない者。一般的には、社会的な関係では多少の建前が必要だが、それを全くしないように見える。とてつもない権力欲のために、いつも問題を起こすトラブルメーカー。",
        "Veroo": "フィルターなし\nあなた、欠点だらけだね?\n欠点の幽霊。ベルは相手をけなすことで有名な幽霊。状況を問わず、他人の欠点を指摘して罵倒する癖がある。",
        "Vivi": "竜族最高の貴族\nその蛮行にしばらく付き合ってあげましょう。\nかつてダーヤに次ぐ序列2位だった銀の竜族。潔癖症なので、いつも周囲を清潔にしようとするが、長い間体調が優れないため、よくくしゃみをしてしまう。ヴィヴィに触れた使徒たちが病気になってしまうのは、体調の優れないヴィヴィがうつしたからだろうか?",
        "xXionx": "黒い魔弾の射手\n光と闇の境界を見て来たのだ!\nエーリアスの黒い力、自称「魔弾の射手」。自分だけの世界に深く浸っている幽霊。一見気難しそうに見えるが、ダークでシリアスなものが好きな趣味さえ合わせてあげれば、簡単に友達になれる。",
        "Yomi": "物語の中の向月葵\n太陽が眠りにつけば、月が世界を照らすのです。\n月の明るいある夜に、偶然出会った月の司祭。ネルの話によると月を崇拝する司祭は昔話の中の存在だというが……時折、教団を訪れて私を慕うところを見ると優しい性格の持ち主のようだ。",
        "Yumimi": "気だるげなハンター\nわぁ~やっぱり草の香りがいいわ~\n自分の状況と境遇に満足して暮らす自給自足型の獣人。獣人の村にもあまり立ち寄らず、森で主に生活しているという。ユミミが空けた家は、獣人の子供たちの遊び場になっている。"
    },
    "en": {
        "Alice": "Fortune Card Expert\nLet me be responsible for your future!\nAn affable phantom who reads cards filled with the power of foresight. Getting a card reading done for fun will lead to certain regret after realizing how unlucky you are",
        "Allet": "Youngest Staff Sergeant\nEverything's been updated with my new address!\nThe youngest staff sergeant of the Monatium Suppression Unit. A dedicated soldier who will carry out any of Canna's orders. Her only flaw is that she does not listen to Elena or Amelia, both of whom outrank Kanna.",
        "Amelia": "The Top Secretary\nThis is Amelia, the mayor's secretary. May I ask the reason for this call?\nThe secretary of the mayor of the elven city, Monatium. A workaholic who runs Monatium for Elena, Sometimes you can see her being a bit too obsessive with Elena... Those who have witnessed this all say that it was terrifying.",
        "Ashur": "The Baking Queen\nThe greatest archwizard of the sprites, Ashur, is on her way!\nThe owner of the best bakery in Sprite. Kingdom and the worst Magic School headmistress. If you don't want to hear an outburst of emotions, it's best to not talk about the bakery.",
        "Aya": "Sage of Perpetual Snow\nDid you come find me because something's troubling you? Well, I'm all ears.\nThe witch called the Sage of Perpetual Snow. Aya is one of the few denizens of Elias capable of thinking deeply, leading to many seeking all types of advice from her. She sometimes says things that cross the line without realizing it.",
        "Belita": "Preeminent Witch\nI'm the Witch Queen. The guardian of the roots.\nThe most dignified queen of the witches. Not just among the witches, but considering Elias as a whole, she is the only entity deserving of the title \"queen.\" She is a role model for the leaders of Elias.",
        "Beni": "Chow Rebels Power\nLeave the heavy lifting to me!\nA bear werebeast who is always easygoing and overenthusiastically scarfing down food. She is so affable that she gets taken advantage of from time to time. She is the lowest-ranking member of the Chow Rebels.",
        "BigWood": "The Bravest Elemental\nProtecting nature...\nA brawny wood elemental. However, if you actually get close enough to have a conversation with her, she apparently says things that send a chill down your spine. She doesn't really have any evil intentions... probably.",
        "Blanchet": "A Blue Rose on Stage\nI hope my acting was flawless.\nBlue rose elemental who is an actress in Monatium. The reason an elemental such as her is able to survive in Monatium is because of her passion and pride in acting. She wants to overcome her weakness a deficiency of various emotional expressions and become an actress beloved by many.",
        "Butter": "Friends are the Best\nC'mon, come play with me! What game shall we play?\nA werebeast with a perpetually cheerful and bright personality. She always tries to make friends. No one has seen Butter angry before... Maybe we'll be able to see it one day though.",
        "Canna": "Arcade Empress\nCommand received!\nSuppression Unit Chief of the elven city, Monatium. It looks like she was a high-ranking soldier before coming to Elias. If it's an order from a superior, she follows it without question.",
        "Carren": "Drama Queen's Downfall\nNo doubt!\nCarren is a \"radical raw foodist\" who believes in eating food in its raw, uncooked state. She once led a raw food trend but fell from grace when she was revealed to be a hypocrite who adds dressing to her food.",
        "Chloe": "Sandbag Doll Expert\nI'm Chloe. And this is Sebastian. Don't get us mixed up.\nA tailor sprite who comes second to none when it comes to fashion. She has a scary obsession with her doll, Sebastian. She's selective about who she hangs out with due to her fussy personality, but she is very thorough when it comes to her work,",
        "Chopi": "Eager Rookie\nI'll get strong, no matter what, and earn their respect!\nA young werebeast who just started her training. The people she views as role models have a few screws loose, but it doesn't seem like she's caught on. Such childish innocence. Perhaps such unassuming natures create heroes?",
        "Cuee": "Cucumber's Ultimate Move\nWell color me cucumber! Have I kept you waiting?\nKyuri is a 'cucumber enthusiast sprite who puts cucumbers in her food. She is trying to make cucumbers a mainstream food within Sprite society, but it seems like a lost cause, considering how divisive they are.",
        "Diana": "Wisdom from Time\nEven closing my eyes has its limits.\nA wise elder trusted and followed by the werebeasts. Denizens say that Diana has had quite a lively past.",
        "Ed": "Eternal Dreamer\nDream with me eternally.\nAn elf dreaming wihtin the life Line Establishing Logic System, Nata, She thinks everything she sees, hears, and feels is a dream, not reality. She uses brain signals to communicate with Nata, and they share their warmth while adapting to the unfamiliar world of Elias together.",
        "Elena": "Elves True Leader\nIf necessary, a fair contract will be established.\nMayor of the elven city, Monatium, A mech-magic engineer who has great pride in her research and inventions. Outwardly, she tries to maintain a good relationship with other races... but it's hard to trust her completely since elves usually lie to further their own agenda.",
        "Epica": "Bard of Elias\nMay I sing your story?\nA wandering bard werebeast of Elias. She always recites stories cheerfully and likes extreme situations. It looks like she found her place within the Order after wandering around in search of new stories and the 'Ultimate Heroine,",
        "Erpin": "Sprite Queen\nHere I am! The guardian of Elias!\nQueen of the sprites. She is a sucker for sweet desserts. Although she can seem hopeless at times and she isn't perfect, she is a sprite who tries her best in her own way. No matter how rude she is, you just can't hate her.",
        "Espi": "Dream-Taping Specialist\nAre you gonna have a good dream for me?\nA dream phantom who can't dream. She constantly seeks fulfillment by peeking into and living vicariously through the dreams of others. She has a bad reputation because there have been many instances where she's crept into the houses of other denizens as they slept.",
        "Festa": "Elias Top Rocker\nI'll win the world over with my music!\nAn artist who rejects anything that restricts her, like rules and regulations, and sings of freedom. She calls herself a 'champion of freedom'... but she is nothing more than a homeless person at a monorail station. It's questionable as to whether or not she ever truly knows the meaning of freedom.",
        "Fricle": "Belita's Advisor\nThe harbinger of destruction-It is me, Fricle!\nThe second-in-command of Witch Kingdom, assisting the Witch Queen. She is always busy planning something and is proud of this aspect of herself. She pays little heed to what others think when it comes to pursuing her vicious ideals.",
        "Gabia": "Quietest Elemental\n(\"Ooh?!\", she mumbles.)\nAn earth elemental of few words. It doesn't look like she's shy. You just can't tell if she's talking because her voice is so small. There are a few elementals who seem to understand what Gabia says.",
        "Haley": "A Self-Proclaimed Elven Vanguard Officer\nDo you pledge walking with me, on the path to peace?\nA retired Elven Army officer who believes she is still on active duty. Due to the PTSD she received from the invasion of Earth, she has become delusional, thinking she now lives in \"Elias\" an allied state. Even now, she continues to work hard to bring peace to her imaginary world.",
        "Hilde": "Perennial Resident Doctor\nHehe. Are you ready for your treatment?\nA long-standing resident at Monatium University Hospital. She frowned upon the use of magic that could instantaneously heal illnesses with a mere utterance of spells, but after coming to Elias, she stopped being stubborn and focused on the Elias medical research method. Her psychological treatments are especially in demand because of her kind and gentle nature",
        "Ifrit": "Obstinate Elemental\nLet's make it sizzle!\nExpert at getting angry without cause or justification. It is rumored that she can adeptly manage her anger and secretly chooses who to be angry with.",
        "Jade": "Don't Tease Me for Being Gullible\nI'll collect them all. A collection of all things knowledge\nDragon who treats knowledge as treasure. A jade dragon. Her greed of knowledge is so great that it makes her unwilling to teach or disseminate information to others. She doesn't have wings despite being a dragon... What could the story behind this be?",
        "Jubee": "No. 1 Honey Producer\nI'm not a bug, bee. I'm a honey bee\nA beast? Insect? No, an elemental commonly found while wandering Elias Forest. There is a high chance of encountering Jubee as you wander through the forest, but it's best not to bother her too much.",
        "Kidian": "Voluntary Outsider\nBeing in the dark isn't so bad.\nA willing outsider among the dragons. An obsidian dragon. She's so used to being alone that she is excessively shy. The way she considers herself worthless evokes sympathy from the people around her.",
        "Kommy": "Reading Queen of The the Werebeasts\nCan Kommy sleep now?\nA very smart Werebeast despite her disheveled appearance.The problem is that she is also quite a klutz. It looks like she has big ambitions... hopefully. they're not too dangerous.",
        "Kyarot": "Artisanal Farmer\nWanna come play in my garden?\nA sprite gardener who can make any crop grow big. She has set up a garden around Yggdrasil and grows giant sugarcanes. She used to disregard the Elves, who supply sugar, but maybe she's changed now?",
        "Lazy": "Working Soul\nYou have work for me to do?\nAn unfortunate elf who is an employee of Monatium City's IT Management Unit, but gets called and dragged away for all kinds of work because she once showed how capable an employee she was.",
        "Leets": "Steel Tempered Ten Thousand Times\nA challenger worthy of the strong... It can be done, right?\nA dragon reborn as steel through endless training. She once had a brave and bold personality, but she has become timid and indecisive for some reason. There might be some sort of trigger, seeing as how glimpses of her former self can be seen from time to time.",
        "Levi": "Part-Time Job Expert\nYes, hello?? Is there a reason you called?\nA witch who works, and works, and works nonstop. The witches treat Levi as the youngest and make her do all kinds of chores. She always looks tired.",
        "MaestroMK2": "Top-Spec Robot\nMaestroMK2: Ready for action.\nA soulless robot. Sometimes MaestroMK2 does something that makes you think they might actually have a soul though. Whether to treat MaestroMK2 as a sentient being or object depends on the individual.",
        "Mago": "Peace-Loving Werebeast\nLet's all get along and play together\nA kind werebeast who enjoys protecting and taking care of her little animal friends. Mago's little friends are well-known for listening to her.",
        "Maison": "Daily Sabbath\nIs this my new home?\nA rest phantom. She always keeps her emotions calm and has a bizarre side to her where she tries to make herself at home wherever she is and wherever she goes. It is unknown as to what significance such a personality holds.",
        "Marie": "Explosives Handler\nHow about blowing everything up that's blocking our way!\nA Sprite Kingdom explorer. Her job is to find relics and treasures, but it doesn't seem as if she's interested in preserving them. She just blows them up. It looks like she has some skeletons in her closet.",
        "Mayo": "Top Collector of Stolen Goods\nMy collection has grown again today.\nA sprite who specializes in collecting things. She collects anything unique, so much so that she even set up her own stolen goods shop. It's said that anything you give to Mayo is hard to get back.",
        "Meluna": "No. 1 in Copyright Earnings\nI'm Meluna- The melon elemental- Sing for me-\nA melon elemental and her pet, Musk. She might look ordinary at first, but it is rumored that she is immensely wealthy somehow. It would be wise to be on her good side.",
        "Momo": "Becoming the Strongest Ninja One Day\nEasy and simple requests are always welcome!\nA werebeast who dreams of becoming the best ninja in Elias, Her skills are on display when she carries out the requests of various denizens, but often makes strange mistakes too. If you have a favor to ask of Momo, make sure to prepare some flower nectar instead of chow.",
        "Mynx": "Clumsy Teacher\nThat's not how you do it!\nA fairly experienced werebeast who is in charge of educating young werebeasts. However, being experienced and teaching are two different things. There are many times when Mynx doesn't know what to teach, so the werebeast students prefer studying on their own.",
        "Naia": "I'm the Life of the Party\nThe world is in need of her! Naia, the water elemental, makes her appearance-!\nLife-of-the-party elemental who brightens the mood around her with a bit of playfulness. You can say that she is Miss Popular in Elias. Her slight lack of seriousness can sometimes make those around her a bit flustered though",
        "Ner": "High Priestess\nFor Yggdrasil, I'll do anything.\nThe benevolent smile of the high priest of the Yggdrasil Order conceals something. She is a perfectionist and strict with those around her. She is always willing to go the extra mile when it comes to anything related to Yggdrasil or the Order.",
        "Patula": "Chef from Hell's Kitchen\nDon't mess around when you're in the kitchen!\nAn apprentice baker at Sprite Kingdom's bakery district. She dreams of becoming the best pastry chef one day as she learns from different bakers, including Ashur. Her personality is not that great since she is always so volatile.",
        "Picora": "Elias Fashionista\nOne day, everyone will envy me!\nA witch who loves excessive styling. After falling in love with the bright and fancy vibe of the surface, she fled the harsh Witch Kingdom and lived in the forest. Her dream is to someday become a fashion influencer on the surface, acknowledged by all witches.",
        "Posher": "Potion Crafting Master\nHehe, drink up! Don't leave a single drop.\nA so-called medicine peddler witch. She brews potions and sells them in her potions shop.Posher's potions are greatly effective but also come with great side effects as well.",
        "RenewaAwaken": "Multidimensional Wandering Elf\nWill you join me in the present to ring in tomorrow?\nAn elf who recently appeared out of nowhere and started working part-time in the ticket booth of Sprite Kingdom's theater. Sometimes you can see her being a bit out of it because she's tired from work, but she is kind to everyone.",
        "Rim": "Dad Joke Expert\nI'm Rim...The phantom of order.\nA phantom that protects the balance of Elias. Whenever someone gets caught up in something big, she appears out of nowhere and lends a hand. She has the most unique sense of humor among the phantoms.",
        "Risty": "Real-life Hacker\nHeh. There's no game I can't beat.\nAn unemployed layabout from Monatium, a pro-gamer, and a self-proclaimed hacker. Once a listless slacker, but after a series of events, she has gained confidence ever since learning about hacking. Skeptical of the typical elven treachery, it turns out she's unexpectedly kind-hearted.",
        "Rohne": "Best Spy?\nIt's your friendly neighborhood spy, Rohne!\nThe best elven spy who looks naive. Sometimes It makes you wonder if she really is the best. No matter how you look at it, she just looks like the worst spy... With her decent nature, she is able to fit in anywhere.",
        "Rude": "Competes with Muscles\nAm I a powerful, and worthy, enough person to follow?\nThe official second-in-command of the dragons. A ruby dragon. There are very few dragons who have ever defeated Rudd to this day. It's not easy to get close to her if you don't like to exercise.",
        "Rufo": "Chow Rebels Knowledge Queen\nDo you need my secret sauce?\nAn arrogant werebeast. Although she always acts detestably, it doesn't seem like all her relationships are bad since she has close friends. She calls herself the brains behind the Chow Rebels.",
        "Sari": "Reaction Master\nStart off by floating an idea.\nYou can't tell what kind of phantom Sari is. She is obsessed with empathizing and going along with the conversation and actions of other phantoms, so maybe this is a clue?",
        "Selline": "Queen of Taunts\nThat expression you made just now was priceless.\nA phantom whose hobby is making fun of others and making them angry. Initially, she sounds friendly, but the closer you listen, the more you realize how incredibly adept she is at getting under your skin. She considers everyone her prey, including other phantoms aside from herself, but she apparently likes to target elves above all.",
        "Shady": "Prankster Extraordinaire\nWhat shall I pull on you today? Hehe!\nPhantoms all want to be her. No other phantom can pull off a prank on the scale of Shaydi's pranks. She mentioned something about ending the world being the ultimate prank.",
        "Shoupan": "Extreme Speedster\nWith Shoupabolt, I can go anywhere!\nA light-speed courier racing across Elias. Enjoys riding the Shoupabolt, zipping from place to place. While she's committed to quick deliveries, she couldn't care less about the safety of the items.",
        "Silphir": "Pride Feeds Me\nI am Silphir, the second-in-command of the dragons!\nA sapphire dragon who always aims for the top spot and challenges the ranks. She may look like an underdog, but she is actually of an incredibly high rank. She is a flawless apostle apart from her obsession with ranks.",
        "Sist": "Budding Swindler\nLooking to buy something? Just let me know, hehe.\nA dragon who buys and sells whatever she can. An amethyst dragon. It seems like she has some sort of lofty goal, but there aren't many who know about it since she keeps a tight lip about it.",
        "Snorky": "Underground Gangster\nIt's time to take charge.\nOnce a notorious gang leader, now a tough witch. She currently serves as the bodyguard of the Master. Only she knows if Snorky truly accepts the Master or secretly dreams of a coup.",
        "Speaki": "A Phantom Whiz at Getting Carried Away\nI'm Ner, the priestess of Yggdrasil! Oh? Who's Speaki?\nA reckless copycat phantom, She is serious about copying a certain target. Although it doesn't seem like she necessarily does this out of ill intent... it seems she doesn't particularly consider the feelings of her target either.",
        "Sylla": "Top Sharpshooter\nDon't underestimate me, the chief of the noble elementals.\nThe coolest wind elemental in Elias. She can sometimes be a bit cruel or overbearing. She is kind of like a big sister to the elementals.",
        "Taida": "Best in Tight Spots\nOh? I- I wasn't fooling around!\nA Monatium City Hall security guard. An elf who is great at slacking off without her superior officer noticing. Her specialty is surfing the web behind Amelia's back. She is extremely thorough in managing her browsing history on Elfnet.",
        "Ui": "The Power of Positivity\nI'm gonna make everyone have only good thoughts!\nThe drizzle elemental with her best friend, the frog, Croakie. Ui always views the world in a positive light and considers all types of adversity or misfortune as insignificant. With Ui there, even with dark and gloomy skies there is a strange brightness in the air.",
        "Velvet": "Power-Enhancing Magic Specialist\nHmm... You seem pretty strong.\nAmong witches who strive for power she... will stop at nothing to attain it. With her, there is a complete absence of pretense, which is somewhat necessary in social relationships. Trouble always follows her due to her intense thirst for power.",
        "Veroo": "No Filter\nYou're a weak one, aren't you?？\nA flaw phantom. Veroo is famous for being a phantom who badmouths others. She has a habit of picking out the flaws of others, regardless of the situation.",
        "Vivi": "A Noble from Dragon Royalty\nThy recklessness... I suppose I may humor it, I trow.\nA silver dragon who was once ranked second to Daya. She always tries to keep her surroundings clean as a germaphobe, but she is always sneezing due to her chronic cold. Could it be that the apostles who have come into contact with Vivi are suffering because of Vivi's chronic cold?",
        "xXionx": "Black Magic Bullet Slinger\nI have seen the boundary between light and darkness!\nThe black light of Elias who calls herself the 'Magic Bullet Slinger'. She's a phantom who is deeply lost in her own world. She may seem difficult at first glance, but it seems easy to befriend her if you cater to her liking for dark and serious things.",
        "Yomi": "Moonflower From the Stories\nWhen the sun falls asleep, the moon illuminates the world.\nA priestess of the moon who I met in a chance encounter one bright, moonlit night. According to Ner, priestesses that shadow the moon are just old wives' tales... But judging by the way she frequently comes to the Order and follows me around, she just seems nice and friendly.",
        "Yumimi": "Lethargic Hunter\nAhhh- I love the smell of grass...\nA self-reliant werebeast who is satisfied with her situation and circumstances. She mostly dwells in the forest and seldom visits the village. Yumimi's house is sometimes used as a playground by some mischievous werebeasts when she's not around,"
    },
};
