// ==========================================
// 嘟嘟臉金蠟筆記事本 - 核心資料庫 (data_core.js)
// 負責：首頁與詳細頁共用的基礎資料、圖片映射、多語系字典
// ==========================================

// ------------------------------------------
// 1. 多語系字典與翻譯系統
// ------------------------------------------
const LANG_DICT = {
    "zh-TW": {
        app_title: "嘟嘟臉金蠟筆記事本", app_subtitle: "祝各位教主日日出金蠟筆", stats_title: "📊 統計與加成資訊",
        stats_stat: "統計", stats_character: "坨坨", stats_attack: "攻", stats_defence: "防", stats_hp: "血",
        stats_critical: "爆", stats_resist: "抗", stats_personality: "🔮 性格：", stats_race: "🧬 種族：",
        stats_position: "🗺️ 站位：", stats_job: "⚔️ 職業：", stats_cell: "🖍️ 金蠟筆格：", stats_crayon: "金蠟筆",
        stats_level: "指定層數:", cell_kind: "格子種類:", level_1st: "第一層", level_2nd: "第二層", level_3st: "第三層",
        total_owned: "已擁有坨坨", crayon_used: "蠟筆消耗量", crayon_needed: "蠟筆需求量",
        crayon_attack: "攻擊", crayon_defence: "防禦", crayon_hp: "血量", crayon_critical: "爆擊", crayon_resist: "爆抗",
        personality_naive: "天真", personality_calm: "冷靜", personality_mad: "狂亂", personality_vivid: "活潑", personality_gloomy: "憂鬱",
        race_witch: "魔女", race_beast: "獸人", race_dragon: "龍族", race_spirit: "魔靈", race_fairy: "妖精", race_elf: "精靈", race_ghost: "幽靈", race_unknown: "???",
        position_front: "前排", position_middle: "中排", position_back: "後排", job_attacker: "輸出", job_defender: "肉盾", job_supporter: "輔助",
        visit_count_prefix: "累計利用回數", maintenance_msg: "🔧 維護更新中...", event_title: "🎪 今期活動",
        auth_offline_title: "當前狀態：單機模式", auth_offline_desc: "紀錄保存在此裝置", auth_online_title: "🟢 已連線雲端", auth_logout: "登出",
        filter_title: "🔍 篩選器", filter_search_placeholder: "搜尋坨坨...", filter_reset: "重置全部篩選", filter_display_mode: "👁️ 版面顯示：",
        filter_btn_all: "全部", filter_btn_show_all: "顯示全部", filter_btn_show_1: "僅第一層", filter_btn_show_2: "僅第二層", filter_btn_show_3: "僅第三層",
        stats_toggle_hint: "點擊展開 / 收起", stats_layer_1_title: "🥇 第一層統計", stats_layer_2_title: "🥈 第二層統計", stats_layer_3_title: "🥉 第三層統計",
        stats_layer_1_rule: "(每格+3%, 蠟筆×2)", stats_layer_2_rule: "(每格+4%, 蠟筆×4)", stats_layer_3_rule: "(每格+5%, 蠟筆×6)",
        stats_global_bonus: "📊 全體屬性加成", stats_need_more_prefix: "尚要 ", stats_need_more_suffix: " 根蠟筆",
        x_label: "台港澳服官方X", official_x_url: "https://x.com/trickcal_TW",
        footer_author: "📝 記事本製作者: 冷笑話幽靈", footer_copyright: "© 遊戲版權: EpidGames & Bilibili", footer_lastupdate: "最後更新日期：06/06/2026",
        "天真": "天真", "冷靜": "冷靜", "狂亂": "狂亂", "活潑": "活潑", "憂鬱": "憂鬱",
        "魔女": "魔女", "獸人": "獸人", "龍族": "龍族", "魔靈": "魔靈", "妖精": "妖精", "精靈": "精靈", "幽靈": "幽靈", "???": "???",
        "前排": "前排", "中排": "中排", "後排": "後排", "輸出": "輸出", "肉盾": "肉盾", "輔助": "輔助",
        "攻擊": "攻擊", "防禦": "防禦", "血量": "血量", "爆擊": "爆擊", "爆抗": "爆抗", "全部": "全部",
        "洛涅": "洛涅", "薇薇": "薇薇", "艾爾芬": "艾爾芬", "錫安": "錫安", "伊弗利特": "伊弗利特", "伊德": "伊德", "佩佩": "佩佩", "佩斯塔": "佩斯塔",
        "修帕": "修帕", "傑德": "傑德", "優米": "優米", "劉美美": "劉美美", "加薇雅": "加薇雅", "卡洛特": "卡洛特", "卡蓮": "卡蓮", "喬菲": "喬菲",
        "基狄恩": "基狄恩", "大師2號": "大師2號", "大木頭": "大木頭", "奈雅": "奈雅", "奶油": "奶油", "布蘭切": "布蘭切", "希拉": "希拉", "希爾德": "希爾德",
        "希瑟圖": "希瑟圖", "希菲爾": "希菲爾", "帕特拉": "帕特拉", "庫洛艾": "庫洛艾", "康娜": "康娜", "愛麗絲": "愛麗絲", "斑尼": "斑尼", "斯皮奇": "斯皮奇",
        "斯諾奇": "斯諾奇", "柯米": "柯米", "桃桃": "桃桃", "梅森": "梅森", "梅露娜": "梅露娜", "海莉": "海莉", "珀榭": "珀榭", "琳": "琳",
        "瑟琳娜": "瑟琳娜", "瑪約": "瑪約", "瑪麗": "瑪麗", "皮可菈": "皮可菈", "盧波": "盧波", "米雪": "米雪", "綾": "綾", "羽伊": "羽伊",
        "艾斯皮": "艾斯皮", "艾琳娜": "艾琳娜", "艾皮卡": "艾皮卡", "艾舒爾": "艾舒爾", "艾蜜莉雅": "艾蜜莉雅", "芙莉可": "芙莉可", "茱蜜": "茱蜜", "莉茲": "莉茲",
        "莎莉": "莎莉", "萊薇": "萊薇", "蒂亞娜": "蒂亞娜", "謝蒂": "謝蒂", "貝魯": "貝魯", "貝麗塔": "貝麗塔", "路德": "路德", "路易": "路易",
        "阿萊特": "阿萊特", "雷吉": "雷吉", "馬爾": "馬爾", "泰達": "泰達", "寧琉": "寧琉", "莉絲蒂": "莉絲蒂", "雷內瓦": "雷內瓦",
        page_title_char_detail: "角色詳細資料", btn_close_page: "⬅️ 關閉此頁", loading: "載入中...",
        crayon_detail_title: "🖍️ 金蠟筆分佈詳情", layer_1_stats: "🥇 第一層屬性", layer_2_stats: "🥈 第二層屬性", layer_3_stats: "🥉 第三層屬性",
        present_title: "🎁 坨坨珍藏品", present_loading: "寶箱開啟中...", btn_letter: "坨坨情信", btn_thought: "教主感想",
        present_select_hint: "請選擇顯示內容...", no_letter_hint: "（這隻坨坨好像還沒寫信給你呢...）", no_thought_hint: "（教主目前還沒寫下對這個珍藏品的感想呢...）",
        present_delivering: "珍藏品正在送遞中...", present_suffix: "的珍藏品", present_error: "⚠️ 珍藏品載入錯誤",
        skill_detail_title: "⚔️ 技能詳細資料", skill_loading: "技能載入中...", skill_normal_attack: "普通攻擊",
        skill_basic: "【基本】", skill_enhanced: "【強化】", skill_passive: "被動技能", skill_admission: "普通技能", skill_graduate: "高級技能",
        costume_default: "預設", costume_prefix: "服裝",
        comment_title: "💬 玩家評價與心得", comment_author_placeholder: "您的暱稱 (留白將以匿名顯示)", comment_content_placeholder: "寫下您對這位坨坨的評價、組隊心得或是發廚發言...",
        btn_submit_comment: "送出評價 🚀", btn_submitting: "傳送中... ⏳", comment_loading: "連線至留言板中...",
        no_comment_hint: "目前還沒有評價，來搶頭香吧！ 🐾", time_just_now: "剛剛", anonymous_leader: "匿名教主#",
        error_no_char: "❌ 未指定角色，請從主頁點擊角色按鈕進入。", error_no_data: "❌ 載入失敗：找不到 INITIAL_DATA。",
        error_char_not_found: "❌ 找不到該角色資料。", error_no_skill_data: "❌ 找不到 skill.js 資料，請確認檔案存在。",
        error_char_skill_not_found: "⚠️ 找不到該角色的技能資料。", alert_empty_comment: "請輸入評價內容！",
        alert_comment_too_long: "評價內容太長囉，請縮減至 500 字以內！", alert_comment_failed: "留言失敗，請稍後再試！", error_load_comment: "讀取留言失敗，請確認資料庫權限設定。"
    },
    "ja": {
        app_title: "トリッカル特級クレヨンノート", app_subtitle: "教主が毎日特級クレヨンを受け取れますように", stats_title: "📊 統計とボーナス情報",
        stats_stat: "統計", stats_character: "使徒", stats_attack: "攻撃", stats_defence: "防御", stats_hp: "HP",
        stats_critical: "会心", stats_resist: "抵抗", stats_personality: "🔮 性格：", stats_race: "🧬 種族：",
        stats_position: "🗺️ 配置：", stats_job: "⚔️ 職業：", stats_cell: "🖍️ 特級クレヨン：", stats_crayon: "特級クレヨン",
        stats_level: "特定ボード:", cell_kind: "ステータス:", level_1st: "1段階目", level_2nd: "2段階目", level_3st: "3段階目",
        total_owned: "所有使徒", crayon_used: "消費クレヨン数", crayon_needed: "必要クレヨン数",
        crayon_attack: "攻撃力", crayon_defence: "防御力", crayon_hp: "HP", crayon_critical: "会心", crayon_resist: "会心抵抗",
        personality_naive: "純粋", personality_calm: "冷静", personality_mad: "狂気", personality_vivid: "活発", personality_gloomy: "憂鬱",
        race_witch: "魔女", race_beast: "獣人", race_dragon: "竜族", race_spirit: "精霊", race_fairy: "妖精", race_elf: "エルフ", race_ghost: "幽霊", race_unknown: "???",
        position_front: "前列", position_middle: "中列", position_back: "後列", job_attacker: "攻撃", job_defender: "守備", job_supporter: "支援",
        visit_count_prefix: "総閲覧数", maintenance_msg: "🔧 メンテナンス中...", event_title: "🎪 開催中のイベント",
        auth_offline_title: "現在の状態：オフラインモード", auth_offline_desc: "データはこの端末に保存されます", auth_online_title: "🟢 クラウドに接続中", auth_logout: "ログアウト",
        filter_title: "🔍 フィルター", filter_search_placeholder: "使徒を検索...", filter_reset: "すべてのフィルターをリセット", filter_display_mode: "👁️ ボード表示：",
        filter_btn_all: "すべて", filter_btn_show_all: "すべて表示", filter_btn_show_1: "1段階目のみ", filter_btn_show_2: "2段階目のみ", filter_btn_show_3: "3段階目のみ",
        stats_toggle_hint: "クリックで展開 / 折りたたみ", stats_layer_1_title: "🥇 1段階目の統計", stats_layer_2_title: "🥈 2段階目の統計", stats_layer_3_title: "🥉 3段階目の統計",
        stats_layer_1_rule: "(各マス+3%, クレヨン×2)", stats_layer_2_rule: "(各マス+4%, クレヨン×4)", stats_layer_3_rule: "(各マス+5%, クレヨン×6)",
        stats_global_bonus: "📊 全体ステータスバフ", stats_need_more_prefix: "必要クレヨン数: ", stats_need_more_suffix: " 本",
        x_label: "公式 X", official_x_url: "https://x.com/trickcal_jp",
        footer_author: "📝 ノート作成者: 冷笑話幽靈", footer_copyright: "© ゲーム著作権: EpidGames & Bilibili", footer_lastupdate: "最終更新日：06/06/2026",
        "天真": "純粋", "冷靜": "冷静", "狂亂": "狂気", "活潑": "活発", "憂鬱": "憂鬱",
        "魔女": "魔女", "獸人": "獣人", "龍族": "竜族", "魔靈": "精霊", "妖精": "妖精", "精靈": "エルフ", "幽靈": "幽霊", "???": "???",
        "前排": "前列", "中排": "中列", "後排": "後列", "輸出": "攻撃", "肉盾": "守備", "輔助": "支援",
        "攻擊": "攻撃", "防禦": "防御", "血量": "HP", "爆擊": "会心", "爆抗": "会心抵抗", "全部": "すべて",
        "洛涅": "ローネ", "薇薇": "ヴィヴィ", "艾爾芬": "エルフィン", "錫安": "シオン・ザ・DB", "伊弗利特": "イフリート", "伊德": "イード", "佩佩": "ベルベット", "佩斯塔": "フェスタ",
        "修帕": "シュパン", "傑德": "ジェイド", "優米": "ヨミ", "劉美美": "ユミミ", "加薇雅": "ガヴィア", "卡洛特": "キャロット", "卡蓮": "カレン", "喬菲": "チョッピー",
        "基狄恩": "ギデオン", "大師2號": "マエストロMK2", "大木頭": "ビッグウッド", "奈雅": "ナイア", "奶油": "バター", "布蘭切": "ブランセ", "希拉": "シーラ", "希爾德": "ヒルデ",
        "希瑟圖": "シスト", "希菲爾": "シルフィール", "帕特拉": "パトラ", "庫洛艾": "クロエ", "康娜": "カンナ", "愛麗絲": "アリス", "斑尼": "ベニー", "斯皮奇": "スピッキー",
        "斯諾奇": "スノキー", "柯米": "コミー", "桃桃": "モモ", "梅森": "メゾン", "梅露娜": "メロナ", "海莉": "ヘイリー", "珀榭": "ポーシャー", "琳": "リム",
        "瑟琳娜": "セリーネ", "瑪約": "マヨ", "瑪麗": "マリー", "皮可菈": "ピコラ", "盧波": "ルポ", "米雪": "ミンス", "綾": "アヤ", "羽伊": "ウイ",
        "艾斯皮": "エスピー", "艾琳娜": "エレナ", "艾皮卡": "エピカ", "艾舒爾": "エシュール", "艾蜜莉雅": "アメリア", "芙莉可": "フリックル", "茱蜜": "ジュビー", "莉茲": "リッツ",
        "莎莉": "サリー", "萊薇": "レヴィ", "蒂亞娜": "ディアナ", "謝蒂": "シェイディ", "貝魯": "ベル", "貝麗塔": "ベリータ", "路德": "ルード", "路易": "キュウイ",
        "阿萊特": "アレット", "雷吉": "レイジー", "馬爾": "マーゴ", "泰達": "タイダー", "寧琉": "ネル", "莉絲蒂": "リスティ", "雷內瓦": "リニュア",
        page_title_char_detail: "使徒詳細データ", btn_close_page: "⬅️ 閉じる", loading: "読み込み中...",
        crayon_detail_title: "🖍️ 特級クレヨン分布詳細", layer_1_stats: "🥇 1段階目ステータス", layer_2_stats: "🥈 2段階目ステータス", layer_3_stats: "🥉 3段階目ステータス",
        present_title: "🎁 使徒の愛用品", present_loading: "宝箱を開封中...", btn_letter: "使徒からの手紙", btn_thought: "教主の感想",
        present_select_hint: "表示内容を選択してください...", no_letter_hint: "（この使徒はまだ手紙を書いていないようです...）", no_thought_hint: "（教主はまだこの愛用品に対する感想を書いていないようです...）",
        present_delivering: "愛用品を配達中...", present_suffix: "の愛用品", present_error: "⚠️ 愛用品読み込みエラー",
        skill_detail_title: "⚔️ スキル詳細", skill_loading: "スキル読み込み中...", skill_normal_attack: "普通攻撃",
        skill_basic: "【基本】", skill_enhanced: "【強化】", skill_passive: "パッシブスキル", skill_admission: "低学年スキル", skill_graduate: "高学年スキル",
        costume_default: "デフォルト", costume_prefix: "衣装",
        comment_title: "💬 教主の評価と感想", comment_author_placeholder: "ニックネーム (空欄の場合は匿名表示)", comment_content_placeholder: "この使徒に対する評価、編成の感想、または愛の叫びを書いてください...",
        btn_submit_comment: "評価を送信 🚀", btn_submitting: "送信中... ⏳", comment_loading: "掲示板に接続中...",
        no_comment_hint: "まだ評価がありません。最初の評価を書きましょう！ 🐾", time_just_now: "たった今", anonymous_leader: "匿名教主#",
        error_no_char: "❌ 使徒が指定されていません。ホーム画面からキャラクターボタンをタップしてください。", error_no_data: "❌ 読み込み失敗：INITIAL_DATAが見つかりません。",
        error_char_not_found: "❌ 該当する使徒データが見つかりません。", error_no_skill_data: "❌ skill.jsのデータが見つかりません。ファイルが存在するか確認してください。",
        error_char_skill_not_found: "⚠️ 該当する使徒のスキルデータが見つかりません。", alert_empty_comment: "評価内容を入力してください！",
        alert_comment_too_long: "評価内容が長すぎます。500文字以内に短縮してください！", alert_comment_failed: "送信に失敗しました。後でもう一度お試しください！", error_load_comment: "コメントの読み込みに失敗しました。データベースの権限設定を確認してください。"
    },
    "en": {
        app_title: "Trickcal Crayon Notepad", app_subtitle: "May the Master get Ultra Crayons daily", stats_title: "📊 Stats & Bonus Info",
        stats_stat: "Stats", stats_character: " Apostle", stats_attack: "ATK", stats_defence: "DEF", stats_hp: "HP",
        stats_critical: "CRIT", stats_resist: "RES", stats_personality: "🔮 Personality:", stats_race: "🧬 Race:",
        stats_position: "🗺️ Position:", stats_job: "⚔️ Class:", stats_cell: "🖍️ Crayon Node:", stats_crayon: "Ultra Crayon",
        stats_level: "Target Board:", cell_kind: "Node Type:", level_1st: "Board 1", level_2nd: "Board 2", level_3st: "Board 3",
        total_owned: "Owned Apostles", crayon_used: "Crayons Used", crayon_needed: "Crayons Needed",
        crayon_attack: "ATK", crayon_defence: "DEF", crayon_hp: "HP", crayon_critical: "CRIT", crayon_resist: "CRIT RES",
        personality_naive: "Pure", personality_calm: "Calm", personality_mad: "Mad", personality_vivid: "Vivid", personality_gloomy: "Gloomy",
        race_witch: "Witch", race_beast: "Beast", race_dragon: "Dragon", race_spirit: "Spirit", race_fairy: "Fairy", race_elf: "Elf", race_ghost: "Ghost", race_unknown: "???",
        position_front: "Front", position_middle: "Mid", position_back: "Back", job_attacker: "Attacker", job_defender: "Tank", job_supporter: "Support",
        visit_count_prefix: "Total Visits", maintenance_msg: "🔧 Under Maintenance...", event_title: "🎪 Current Event",
        auth_offline_title: "Status: Offline Mode", auth_offline_desc: "Data saved locally", auth_online_title: "🟢 Connected to Cloud", auth_logout: "Logout",
        filter_title: "🔍 Filter", filter_search_placeholder: "Search Apostle...", filter_reset: "Reset All", filter_display_mode: "👁️ View Mode:",
        filter_btn_all: "All", filter_btn_show_all: "Show All", filter_btn_show_1: "Board 1 Only", filter_btn_show_2: "Board 2 Only", filter_btn_show_3: "Board 3 Only",
        stats_toggle_hint: "Click to Expand / Collapse", stats_layer_1_title: "🥇 Board 1 Stats", stats_layer_2_title: "🥈 Board 2 Stats", stats_layer_3_title: "🥉 Board 3 Stats",
        stats_layer_1_rule: "(Node+3%, Crayon×2)", stats_layer_2_rule: "(Node+4%, Crayon×4)", stats_layer_3_rule: "(Node+5%, Crayon×6)",
        stats_global_bonus: "📊 Global Stat Bonus", stats_need_more_prefix: "Need ", stats_need_more_suffix: " Crayons",
        x_label: "Official Global X", official_x_url: "https://x.com/trickcal_en",
        footer_author: "📝 Author: 冷笑話幽靈", footer_copyright: "© Copyright: EpidGames & Bilibili", footer_lastupdate: "last updated on: 06/06/2026",
        "天真": "Innocence", "冷靜": "Composed", "狂亂": "Madness", "活潑": "Vivacious", "憂鬱": "Depressed",
        "魔女": "Witch", "獸人": "Werebeast", "龍族": "Dragon", "魔靈": "Elemental", "妖精": "Sprite", "精靈": "Elf", "幽靈": "Phantom", "???": "???",
        "前排": "Front", "中排": "Middle", "後排": "Back", "輸出": "DPS", "肉盾": "Tank", "輔助": "Support",
        "攻擊": "ATK", "防禦": "DEF", "血量": "HP", "爆擊": "CRIT", "爆抗": "CRIT RES", "全部": "All",
        "洛涅": "Rohne", "薇薇": "Vivi", "艾爾芬": "Erpin", "錫安": "xXionx", "伊弗利特": "Ifrit", "伊德": "ED", "佩佩": "Velvet", "佩斯塔": "Festa",
        "修帕": "Shoupan", "傑德": "Jade", "優米": "Yomi", "劉美美": "Yumimi", "加薇雅": "Gabia", "卡洛特": "Kyarot", "卡蓮": "Carren", "喬菲": "Chopi",
        "基狄恩": "Kidian", "大師2號": "Maestro Mk.2", "大木頭": "Big Wood", "奈雅": "Naia", "奶油": "Butter", "布蘭切": "Blanchet", "希拉": "Sylla", "希爾德": "Hilde",
        "希瑟圖": "Sist", "希菲爾": "Silphir", "帕特拉": "Patula", "庫洛艾": "Chloe", "康娜": "Canna", "愛麗絲": "Alice", "斑尼": "Beni", "斯皮奇": "Speaki",
        "斯諾奇": "Snorky", "柯米": "Kommy", "桃桃": "Momo", "梅森": "Maison", "梅露娜": "Meluna", "海莉": "Haley", "珀榭": "Posher", "琳": "Rim",
        "瑟琳娜": "Selene", "瑪約": "Mayo", "瑪麗": "Marie", "皮可菈": "Picora", "盧波": "Rufo", "米雪": "Mynx", "綾": "Aya", "羽伊": "Ui",
        "艾斯皮": "Espi", "艾琳娜": "Elena", "艾皮卡": "Epica", "艾舒爾": "Ashur", "艾蜜莉雅": "Amelia", "芙莉可": "Fricle", "茱蜜": "Jubee", "莉茲": "Leets",
        "莎莉": "Sari", "萊薇": "Levi", "蒂亞娜": "Diana", "謝蒂": "Shaydi", "貝魯": "Veroo", "貝麗塔": "Belita", "路德": "Rudd", "路易": "Kyuri",
        "阿萊特": "Allet", "雷吉": "Layze", "馬爾": "Mago", "泰達": "Taida", "寧琉": "Ner", "莉絲蒂": "Risty", "雷內瓦": "Renewa",
        page_title_char_detail: "Apostle Details", btn_close_page: "⬅️ Close", loading: "Loading...",
        crayon_detail_title: "🖍️ Ultra Crayon Details", layer_1_stats: "🥇 Board 1 Stats", layer_2_stats: "🥈 Board 2 Stats", layer_3_stats: "🥉 Board 3 Stats",
        present_title: "🎁 Apostle's Cherished Items", present_loading: "Opening chest...", btn_letter: "Apostle's Letter", btn_thought: "Master's Thoughts",
        present_select_hint: "Please select content to display...", no_letter_hint: "(This Apostle hasn't written a letter to you yet...)", no_thought_hint: "(The Master hasn't shared their thoughts on this item yet...)",
        present_delivering: "Cherished item is being delivered...", present_suffix: "'s Cherished Item", present_error: "⚠️ Cherished Item Load Error",
        skill_detail_title: "⚔️ Skill Details", skill_loading: "Loading skills...", skill_normal_attack: "Normal ATK",
        skill_basic: "[Basic]", skill_enhanced: "[Enhance]", skill_passive: "Passive Skill", costume_default: "Default", costume_prefix: "Outfit ",
        skill_admission: "Freshman Skill", skill_graduate: "Senior Skill",
        comment_title: "💬 Master Reviews & Thoughts", comment_author_placeholder: "Your Nickname (Leave blank for anonymous)", comment_content_placeholder: "Write your review, team comp tips, or share your love for this Apostle...",
        btn_submit_comment: "Submit Review 🚀", btn_submitting: "Submitting... ⏳", comment_loading: "Connecting to message board...",
        no_comment_hint: "No reviews yet. Be the first to leave one! 🐾", time_just_now: "Just now", anonymous_leader: "Anon Leader #",
        error_no_char: "❌ Apostle not specified. Please enter via the home page.", error_no_data: "❌ Load Failed: INITIAL_DATA not found.",
        error_char_not_found: "❌ Apostle data not found.", error_no_skill_data: "❌ skill.js not found. Please check if the file exists.",
        error_char_skill_not_found: "⚠️ Skill data for this Apostle not found.", alert_empty_comment: "Please enter your review content!",
        alert_comment_too_long: "Review content is too long. Please keep it under 500 characters!", alert_comment_failed: "Failed to submit. Please try again later!", error_load_comment: "Failed to load comments. Please check database permissions."
    }
};

const currentLang = localStorage.getItem('user_lang') || 'zh-TW';
function t(key) { return LANG_DICT[currentLang][key] || key; }

// ------------------------------------------
// 2. 角色基本屬性與金蠟筆分布
// ------------------------------------------
const INITIAL_DATA = [
    { name: "洛涅", personality: "天真", race: "精靈", position: "前排", job: "肉盾", layer1: ["血量", "爆擊"], layer2: ["防禦", "爆擊", "爆抗"], layer3: ["攻擊", "防禦", "血量", "爆擊"] },
    { name: "薇薇", personality: "天真", race: "龍族", position: "前排", job: "肉盾", layer1: ["血量", "爆擊"], layer2: ["防禦", "爆擊", "爆抗"], layer3: ["攻擊", "防禦", "血量", "爆擊"] },
    { name: "卡洛特", personality: "天真", race: "妖精", position: "後排", job: "輔助", layer1: ["攻擊", "血量"], layer2: ["攻擊", "防禦", "爆抗"], layer3: ["攻擊", "防禦", "爆擊", "爆抗"] },
    { name: "奈雅", personality: "天真", race: "魔靈", position: "中排", job: "輔助", layer1: ["血量", "爆擊"], layer2: ["防禦", "爆擊", "爆抗"], layer3: ["攻擊", "防禦", "血量", "爆擊"] },
    { name: "艾爾芬", personality: "天真", race: "妖精", position: "後排", job: "輸出", layer1: ["攻擊", "防禦"], layer2: ["血量", "攻擊", "防禦"], layer3: ["攻擊", "血量", "爆擊", "爆抗"] },
    { name: "馬爾", personality: "天真", race: "獸人", position: "中排", job: "輔助", layer1: ["攻擊", "血量"], layer2: ["攻擊", "防禦", "爆抗"], layer3: ["攻擊", "防禦", "爆擊", "爆抗"] },
    { name: "加薇雅", personality: "天真", race: "魔靈", position: "中排", job: "輔助", layer1: ["攻擊", "血量"], layer2: ["攻擊", "防禦", "爆抗"], layer3: ["攻擊", "爆擊", "防禦", "爆抗"] },
    { name: "希菲爾", personality: "天真", race: "龍族", position: "中排", job: "輸出", layer1: ["爆擊", "血量"], layer2: ["爆擊", "防禦", "爆抗"], layer3: ["攻擊", "爆擊", "血量", "防禦"] },
    { name: "斯皮奇", personality: "天真", race: "幽靈", position: "後排", job: "輸出", layer1: ["攻擊", "防禦"], layer2: ["攻擊", "防禦", "血量"], layer3: ["攻擊", "血量", "爆擊", "爆抗"] },
    { name: "海莉", personality: "天真", race: "精靈", position: "中排", job: "輸出", layer1: ["防禦", "爆抗"], layer2: ["攻擊", "血量", "爆擊"], layer3: ["攻擊", "防禦", "血量", "爆抗"] },
    { name: "大木頭", personality: "天真", race: "魔靈", position: "前排", job: "肉盾", layer1: ["攻擊", "血量"], layer2: ["攻擊", "防禦", "爆抗"], layer3: ["攻擊", "防禦", "爆擊", "爆抗"] },
    { name: "阿萊特", personality: "天真", race: "精靈", position: "前排", job: "肉盾", layer1: ["爆擊", "爆抗"], layer2: ["爆擊", "血量", "爆抗"], layer3: ["爆擊", "防禦", "血量", "爆抗"] },
    { name: "莎莉", personality: "天真", race: "幽靈", position: "中排", job: "輸出", layer1: ["血量", "爆擊"], layer2: ["防禦", "爆擊", "爆抗"], layer3: ["攻擊", "防禦", "血量", "爆擊"] },
    { name: "路易", personality: "天真", race: "妖精", position: "中排", job: "輔助", layer1: ["攻擊", "血量"], layer2: ["攻擊", "防禦", "爆抗"], layer3: ["攻擊", "防禦", "爆擊", "爆抗"] },
    { name: "修帕", personality: "活潑", race: "妖精", position: "後排", job: "輔助", layer1: ["爆擊", "爆抗"], layer2: ["血量", "爆擊", "爆抗"], layer3: ["防禦", "血量", "爆擊", "爆抗"] },
    { name: "奶油", personality: "活潑", race: "獸人", position: "後排", job: "輸出", layer1: ["攻擊", "防禦"], layer2: ["攻擊", "防禦", "血量"], layer3: ["攻擊", "血量", "爆擊", "爆抗"] },
    { name: "桃桃", personality: "活潑", race: "獸人", position: "後排", job: "輸出", layer1: ["攻擊", "血量"], layer2: ["攻擊", "防禦", "爆抗"], layer3: ["攻擊",  "防禦", "爆擊", "爆抗"] },
    { name: "瑟琳娜", personality: "活潑", race: "幽靈", position: "前排", job: "肉盾", layer1: ["攻擊", "防禦"], layer2: ["攻擊", "防禦", "血量"], layer3: ["攻擊", "血量", "爆擊", "爆抗"] },
    { name: "羽伊", personality: "活潑", race: "魔靈", position: "中排", job: "輔助", layer1: ["爆擊", "爆抗"], layer2: ["血量", "爆擊", "爆抗"], layer3: ["防禦", "血量", "爆擊", "爆抗"] },
    { name: "艾皮卡", personality: "活潑", race: "獸人", position: "中排", job: "輸出", layer1: ["爆擊", "爆抗"], layer2: ["血量", "爆擊", "爆抗"], layer3: ["防禦", "血量", "爆擊", "爆抗"] },
    { name: "路德", personality: "活潑", race: "龍族", position: "前排", job: "肉盾", layer1: ["血量", "爆擊"], layer2: ["防禦", "爆擊", "爆抗"], layer3: ["攻擊", "防禦", "血量", "爆擊"] },
    { name: "康娜", personality: "活潑", race: "精靈", position: "後排", job: "輸出", layer1: ["防禦", "爆抗"], layer2: ["攻擊", "血量", "爆擊"], layer3: ["攻擊", "防禦", "血量", "爆抗"] },
    { name: "斑尼", personality: "活潑", race: "獸人", position: "前排", job: "輸出", layer1: ["血量", "爆擊"], layer2: ["防禦", "爆擊", "爆抗"], layer3: ["攻擊", "防禦", "血量", "爆擊"] },
    { name: "盧波", personality: "活潑", race: "獸人", position: "中排", job: "輸出", layer1: ["爆擊", "爆抗"], layer2: ["血量", "爆擊", "爆抗"], layer3: ["防禦", "血量", "爆擊", "爆抗"] },
    { name: "茱蜜", personality: "活潑", race: "魔靈", position: "中排", job: "輸出", layer1: ["攻擊", "防禦"], layer2: ["攻擊", "防禦", "血量"], layer3: ["攻擊", "血量", "爆擊", "爆抗"] },
    { name: "卡蓮", personality: "活潑", race: "妖精", position: "後排", job: "輔助", layer1: ["爆擊", "爆抗"], layer2: ["血量", "爆擊", "爆抗"], layer3: ["防禦", "血量", "爆擊", "爆抗"] },
    { name: "泰達", personality: "活潑", race: "精靈", position: "後排", job: "輸出", layer1: ["攻擊", "血量"], layer2: ["攻擊", "防禦", "爆抗"], layer3: ["攻擊", "防禦", "爆擊", "爆抗"] },
    { name: "瑪麗", personality: "活潑", race: "妖精", position: "中排", job: "輸出", layer1: ["攻擊", "血量"], layer2: ["攻擊", "防禦", "爆抗"], layer3: ["攻擊", "防禦", "爆擊", "爆抗"] },
    { name: "米雪", personality: "活潑", race: "獸人", position: "前排", job: "輸出", layer1: ["攻擊", "血量"], layer2: ["攻擊", "防禦", "爆抗"], layer3: ["攻擊", "防禦", "爆擊", "爆抗"] },
    { name: "伊德", personality: "冷靜", race: "精靈", position: "前排", job: "肉盾", layer1: ["攻擊", "防禦"], layer2: ["攻擊", "防禦", "血量"], layer3: ["攻擊", "血量", "爆擊", "爆抗"] },
    { name: "艾琳娜", personality: "冷靜", race: "精靈", position: "中排", job: "輸出", layer1: ["攻擊", "防禦"], layer2: ["攻擊", "防禦", "血量"], layer3: ["攻擊", "血量", "爆擊", "爆抗"] },
    { name: "佩佩", personality: "冷靜", race: "魔女", position: "前排", job: "肉盾", layer1: ["爆擊", "爆抗"], layer2: ["血量", "爆擊", "爆抗"], layer3: ["防禦", "血量", "爆擊", "爆抗"] },
    { name: "希拉", personality: "冷靜", race: "魔靈", position: "後排", job: "輸出", layer1: ["攻擊", "血量"], layer2: ["攻擊", "防禦", "爆抗"], layer3: ["攻擊", "防禦", "爆擊", "爆抗"] },
    { name: "皮可菈", personality: "冷靜", race: "魔女", position: "後排", job: "輔助", layer1: ["防禦", "爆抗"], layer2: ["攻擊", "血量", "爆擊"], layer3: ["攻擊", "防禦", "血量", "爆抗"] },
    { name: "艾蜜莉雅", personality: "冷靜", race: "精靈", position: "後排", job: "輔助", layer1: ["防禦", "爆抗"], layer2: ["攻擊", "血量", "爆擊"], layer3: ["攻擊", "防禦", "血量", "爆抗"] },
    { name: "芙莉可", personality: "冷靜", race: "魔女", position: "中排", job: "輸出", layer1: ["攻擊", "血量"], layer2: ["攻擊", "防禦", "爆抗"], layer3: ["攻擊", "防禦", "爆擊", "爆抗"] },
    { name: "綾", personality: "冷靜", race: "魔女", position: "中排", job: "輸出", layer1: ["攻擊", "防禦"], layer2: ["攻擊", "防禦", "血量"], layer3: ["攻擊", "血量", "爆擊", "爆抗"] },
    { name: "帕特拉", personality: "冷靜", race: "妖精", position: "前排", job: "輸出", layer1: ["攻擊", "防禦"], layer2: ["攻擊", "防禦", "血量"], layer3: ["攻擊", "血量", "爆擊", "爆抗"] },
    { name: "梅露娜", personality: "冷靜", race: "魔靈", position: "後排", job: "輔助", layer1: ["攻擊", "血量"], layer2: ["攻擊", "防禦", "爆抗"], layer3: ["攻擊", "防禦", "爆擊", "爆抗"] },
    { name: "傑德", personality: "冷靜", race: "龍族", position: "中排", job: "輸出", layer1: ["防禦", "爆抗"], layer2: ["攻擊", "血量", "爆擊"], layer3: ["攻擊", "防禦", "血量", "爆抗"] },
    { name: "艾斯皮", personality: "冷靜", race: "幽靈", position: "中排", job: "輔助", layer1: ["爆擊", "爆抗"], layer2: ["血量", "爆擊", "爆抗"], layer3: ["防禦", "血量", "爆擊", "爆抗"] },
    { name: "雷吉", personality: "冷靜", race: "精靈", position: "後排", job: "輸出", layer1: ["防禦", "爆抗"], layer2: ["攻擊", "血量", "爆擊"], layer3: ["攻擊", "防禦", "血量", "爆抗"] },
    { name: "瑪約", personality: "狂亂", race: "妖精", position: "後排", job: "輸出", layer1: ["防禦", "爆抗"], layer2: ["攻擊", "血量", "爆擊"], layer3: ["攻擊", "防禦", "血量", "爆抗"] },
    { name: "莉茲", personality: "狂亂", race: "龍族", position: "前排", job: "輸出", layer1: ["攻擊", "血量"], layer2: ["攻擊", "防禦", "爆抗"], layer3: ["攻擊", "防禦", "爆擊", "爆抗"] },
    { name: "謝蒂", personality: "狂亂", race: "幽靈", position: "前排", job: "輸出", layer1: ["攻擊", "防禦"], layer2: ["攻擊", "防禦", "血量"], layer3: ["攻擊", "血量", "爆擊", "爆抗"] },
    { name: "庫洛艾", personality: "狂亂", race: "妖精", position: "前排", job: "肉盾", layer1: ["血量", "爆擊"], layer2: ["防禦", "爆擊", "爆抗"], layer3: ["攻擊", "防禦", "血量", "爆擊"] },
    { name: "愛麗絲", personality: "狂亂", race: "幽靈", position: "中排", job: "輸出", layer1: ["血量", "爆擊"], layer2: ["防禦", "爆擊", "爆抗"], layer3: ["攻擊", "防禦", "血量", "爆擊"] },
    { name: "蒂亞娜", personality: "狂亂", race: "獸人", position: "中排", job: "輔助", layer1: ["爆擊", "爆抗"], layer2: ["血量", "爆擊", "爆抗"], layer3: ["防禦", "血量", "爆擊", "爆抗"] },
    { name: "貝麗塔", personality: "狂亂", race: "魔女", position: "後排", job: "輸出", layer1: ["血量", "爆擊"], layer2: ["防禦", "爆擊", "爆抗"], layer3: ["攻擊", "防禦", "血量", "爆擊"] },
    { name: "希瑟圖", personality: "狂亂", race: "龍族", position: "中排", job: "輸出", layer1: ["爆擊", "爆抗"], layer2: ["血量", "爆擊", "爆抗"], layer3: ["爆擊", "防禦", "血量", "爆抗"] },
    { name: "大師2號", personality: "狂亂", race: "精靈", position: "前排", job: "肉盾", layer1: ["血量", "爆擊"], layer2: ["防禦", "爆擊", "爆抗"], layer3: ["攻擊", "防禦", "血量", "爆擊"] },
    { name: "梅森", personality: "狂亂", race: "幽靈", position: "後排", job: "輸出", layer1: ["爆擊", "爆抗"], layer2: ["血量", "爆擊", "爆抗"], layer3: ["防禦", "血量", "爆擊", "爆抗"] },
    { name: "伊弗利特", personality: "狂亂", race: "魔靈", position: "前排", job: "輸出", layer1: ["防禦", "爆抗"], layer2: ["攻擊", "血量", "爆擊"], layer3: ["攻擊", "防禦", "血量", "爆抗"] },
    { name: "劉美美", personality: "狂亂", race: "獸人", position: "後排", job: "輸出", layer1: ["血量", "爆擊"], layer2: ["防禦", "爆擊", "爆抗"], layer3: ["攻擊", "防禦", "血量", "爆擊"] },
    { name: "錫安", personality: "憂鬱", race: "幽靈", position: "後排", job: "輸出", layer1: ["防禦", "爆抗"], layer2: ["攻擊", "血量", "爆擊"], layer3: ["攻擊", "防禦", "血量", "爆抗"] },
    { name: "基狄恩", personality: "憂鬱", race: "龍族", position: "前排", job: "輸出", layer1: ["防禦", "爆抗"], layer2: ["攻擊", "血量", "爆擊"], layer3: ["攻擊", "防禦", "血量", "爆抗"] },
    { name: "布蘭切", personality: "憂鬱", race: "魔靈", position: "中排", job: "輸出", layer1: ["血量", "爆擊"], layer2: ["防禦", "爆擊", "爆抗"], layer3: ["攻擊", "防禦", "血量", "爆擊"] },
    { name: "琳", personality: "憂鬱", race: "幽靈", position: "前排", job: "輸出", layer1: ["爆擊", "爆抗"], layer2: ["血量", "爆擊", "爆抗"], layer3: ["防禦", "血量", "爆擊", "爆抗"] },
    { name: "優米", personality: "憂鬱", race: "???", position: "中排", job: "輔助", layer1: ["攻擊", "防禦"], layer2: ["攻擊", "防禦", "血量"], layer3: ["攻擊", "防禦", "血量", "爆擊"] },
    { name: "希爾德", personality: "憂鬱", race: "精靈", position: "中排", job: "輔助", layer1: ["攻擊", "血量"], layer2: ["攻擊", "防禦", "爆抗"], layer3: ["攻擊", "防禦", "爆擊", "爆抗"] },
    { name: "柯米", personality: "憂鬱", race: "獸人", position: "前排", job: "肉盾", layer1: ["防禦", "爆抗"], layer2: ["攻擊", "血量", "爆擊"], layer3: ["攻擊", "防禦", "血量", "爆抗"] },
    { name: "珀榭", personality: "憂鬱", race: "魔女", position: "後排", job: "輔助", layer1: ["防禦", "爆抗"], layer2: ["攻擊", "血量", "爆擊"], layer3: ["攻擊", "防禦", "血量", "爆抗"] },
    { name: "艾舒爾", personality: "憂鬱", race: "妖精", position: "後排", job: "輸出", layer1: ["爆擊", "爆抗"], layer2: ["血量", "爆擊", "爆抗"], layer3: ["防禦", "血量", "爆擊", "爆抗"] },
    { name: "斯諾奇", personality: "憂鬱", race: "魔女", position: "前排", job: "肉盾", layer1: ["攻擊", "防禦"], layer2: ["攻擊", "防禦", "血量"], layer3: ["攻擊", "血量", "爆擊", "爆抗"] },
    { name: "貝魯", personality: "憂鬱", race: "幽靈", position: "中排", job: "輸出", layer1: ["攻擊", "防禦"], layer2: ["攻擊", "防禦", "血量"], layer3: ["攻擊", "血量", "爆擊", "爆抗"] },
    { name: "佩斯塔", personality: "憂鬱", race: "精靈", position: "前排", job: "輔助", layer1: ["攻擊", "防禦"], layer2: ["攻擊", "防禦", "血量"], layer3: ["攻擊", "血量", "爆擊", "爆抗"] },
    { name: "萊薇", personality: "憂鬱", race: "魔女", position: "中排", job: "輸出", layer1: ["爆擊", "爆抗"], layer2: ["血量", "爆擊", "爆抗"], layer3: ["防禦", "血量", "爆擊", "爆抗"] },
    { name: "喬菲", personality: "憂鬱", race: "獸人", position: "中排", job: "輸出", layer1: ["防禦", "爆抗"], layer2: ["攻擊", "血量", "爆擊"], layer3: ["攻擊", "防禦", "血量", "爆抗"] },
    { name: "寧琉", personality: "狂亂", race: "妖精", position: "前排", job: "輔助", layer1: ["攻擊", "防禦"], layer2: ["攻擊", "防禦", "血量"], layer3: ["攻擊", "血量", "爆擊", "爆抗"] },
    { name: "莉絲蒂", personality: "憂鬱", race: "精靈", position: "後排", job: "輸出", layer1: ["攻擊", "防禦"], layer2: ["攻擊", "防禦", "血量"], layer3: ["攻擊", "血量", "爆擊", "爆抗"] },
    { name: "雷內瓦", personality: "狂亂", race: "精靈", position: "中排", job: "輸出", layer1: ["攻擊", "防禦"], layer2: ["攻擊", "防禦", "血量"], layer3: ["攻擊", "血量", "爆擊", "爆抗"], releaseDate: "2026-06-18T17:00:00+09:00" }
];

const CV_MAP = {
    "洛涅": "田向結月", "薇薇": "新井里美", "艾爾芬": "木野日菜", "錫安": "上坂すみれ", "伊弗利特": "安堂ななこ", "伊德": "内田真礼", "佩佩": "上田瞳", "佩斯塔": "仁見紗綾",
    "修帕": "大空直美", "傑德": "行成とあ", "優米": "高野麻里佳", "劉美美": "兼田めぐみ", "加薇雅": "大谷衣里奈", "卡洛特": "牧野由依", "卡蓮": "咲谷怜奈", "喬菲": "漆山ゆうき",
    "基狄恩": "鈴木愛唯", "大師2號": "田中音緒", "大木頭": "上田瞳", "奈雅": "佐伯伊織", "奶油": "長月あおい", "布蘭切": "和氣あず未", "希拉": "大木咲絵子", "希爾德": "秦佐和子",
    "希瑟圖": "野口瑠璃子", "希菲爾": "葵あずさ", "帕特拉": "大園朱花子", "庫洛艾": "田村ゆかり", "康娜": "岡本美歌", "愛麗絲": "小見川千明", "斑尼": "熊崎愛", "斯皮奇": "小坂井祐莉絵",
    "斯諾奇": "高柳知葉", "柯米": "河瀨茉希", "桃桃": "平塚紗依", "梅森": "赤堀実華琉", "梅露娜": "美坂朱音", "海莉": "衣川里佳", "珀榭": "優木かな", "琳": "渕上舞",
    "瑟琳娜": "石上靜香", "瑪約": "船戸ゆり絵", "瑪麗": "野村真悠華", "皮可菈": "小澤亜李", "盧波": "木村千咲", "米雪": "咲咲谷怜奈", "綾": "日笠陽子", "羽伊": "長縄まりあ",
    "艾斯皮": "內海まり", "艾琳娜": "塚田悠衣", "艾皮卡": "日高里菜", "艾舒爾": "長尾玲奈", "艾蜜莉雅": "中林新夏", "芙莉可": "百瀨帆南", "茱蜜": "山田聖奈", "莉茲": "藤本侑里",
    "莎莉": "漆山ゆうき", "萊薇": "上永紗也華", "蒂亞娜": "立花日菜", "謝蒂": "山城リアン", "貝魯": "若山なつみ", "貝麗塔": "松岡美里", "路德": "渡部惠子", "路易": "兼田めぐみ",
    "阿萊特": "若山なつみ", "雷吉": "大園朱花子", "馬爾": "花咲心優", "泰達": "赤堀実華琉", "寧琉": "アンデルソンゆり子", "莉絲蒂": "黒沢ともよ", "雷內瓦": "花守ゆみり"
};

const GRADE_MAP = {
    "洛涅": "3", "薇薇": "3", "艾爾芬": "3", "錫安": "3", "伊弗利特": "3", "伊德": "3", "佩佩": "3", "佩斯塔": "3",
    "修帕": "3", "傑德": "3", "優米": "3", "劉美美": "2", "加薇雅": "3", "卡洛特": "3", "卡蓮": "2", "喬菲": "2",
    "基狄恩": "3", "大師2號": "2", "大木頭": "2", "奈雅": "3", "奶油": "3", "布蘭切": "3", "希拉": "3", "希爾德": "3",
    "希瑟圖": "3", "希菲爾": "3", "帕特拉": "1", "庫洛艾": "3", "康娜": "3", "愛麗絲": "3", "斑尼": "Beni", "斯皮奇": "3",
    "斯諾奇": "3", "柯米": "3", "桃桃": "3", "梅森": "1", "梅露娜": "2", "海莉": "3", "珀榭": "3", "琳": "3",
    "瑟琳娜": "3", "瑪約": "3", "瑪麗": "2", "皮可菈": "3", "盧波": "3", "米雪": "1", "綾": "3", "羽伊": "3",
    "艾斯皮": "2", "艾琳娜": "3", "艾皮卡": "3", "艾舒爾": "3", "艾蜜莉雅": "3", "芙莉可": "3", "茱蜜": "2", "莉茲": "3",
    "莎莉": "2", "萊薇": "3", "蒂亞娜": "3", "謝蒂": "3", "貝魯": "1", "貝麗塔": "3", "路德": "3", "路易": "1",
    "阿萊特": "2", "雷吉": "2", "馬爾": "3", "泰達": "2", "寧琉": "3", "莉絲蒂": "3", "雷內瓦": "3"
};

const ELDAIN_LIST = ['綾', '庫洛艾', '艾皮卡', '伊德', '羽依', '薇薇', '錫安', '優米', '雷內瓦'];

const FOOD_MAP = {
    "Alice": { super: "有機檸檬茶", special: ["檸檬茶", "幽靈布丁", "惡靈布丁"] },
    "Allet": { super: "ANSA太空食品", special: ["太空食品", "肉桂口味糖球", "肉桂口味健康糖球"] },
    "Amelia": { super: "ANSA太空食品", special: ["太空食品", "巧克力冰淇淋", "深黑巧克力冰淇淋"] },
    "Ashur": { super: "UFC炸蔬菜", special: ["UFC炸胡蘿蔔", "焦糖爆米花", "追劇焦糖爆米花"] },
    "Aya": { super: "三重薄荷冰淇淋", special: ["薄荷巧克力冰淇淋", "巧克力冰淇淋", "深黑巧克力冰淇淋"] },
    "Belita": { super: "草莓切片蛋糕", special: ["草莓蛋糕", "巧克力冰淇淋", "深黑巧克力冰淇淋"] },
    "Beni": { super: "甜甜蜂蜜罐", special: ["蜂蜜罐", "蜂蜜大蒜鮭魚", "皇家蜂蜜大蒜鮭魚"] },
    "BigWood": { super: "椰子萬能青汁", special: ["椰子松針粥", "一碗米飯", "一碗糯米飯"] },
    "Blanchet": { super: "有機檸檬茶", special: ["檸檬茶", "寶石塔", "寶石蛋塔"] },
    "Butter": { super: "追劇焦糖爆米花", special: ["焦糖爆米花", "獸糧罐頭", "高級獸糧罐頭"] },
    "Canna": { super: "一碗糯米飯", special: ["一碗米飯", "烤漫畫肉", "烤海賊漫畫肉"] },
    "Carren": { super: "UFC炸蔬菜", special: ["UFC炸胡蘿蔔", "草莓蛋糕", "草莓切片蛋糕"] },
    "Chloe": { super: "愛心扭結麵包", special: ["扭結麵包", "檸檬茶", "有機檸檬茶"] },
    "Chopi": { super: "烤海賊漫畫肉", special: ["烤漫畫肉", "獸糧罐頭", "高級獸糧罐頭"] },
    "Cuee": "無",
    "Diana": { super: "烤海賊漫畫肉", special: ["烤漫畫肉", "扭結麵包", "愛心扭結麵包"] },
    "Ed": { super: "一級祕密葡萄汁", special: ["祕密葡萄汁", "UFC炸胡蘿蔔", "UFC炸蔬菜"] },
    "Elena": { super: "滾燙的冰美式咖啡", special: ["溫熱的冰美式咖啡", "太空食品", "ANSA太空食品"] },
    "Epica": { super: "追劇焦糖爆米花", special: ["焦糖爆米花", "烤漫畫肉", "烤海賊漫畫肉"] },
    "Erpin": { super: "草莓切片蛋糕", special: ["草莓蛋糕", "巧克力冰淇淋", "深黑巧克力冰淇淋"] },
    "Espi": { super: "深黑巧克力冰淇淋", special: ["巧克力冰淇淋", "UFC炸胡蘿蔔", "UFC炸蔬菜"] },
    "Festa": { super: "氫氣炸豬排", special: ["空氣炸豬排", "祕密葡萄汁", "一級祕密葡萄汁"] },
    "Fricle": { super: "927穀麵茶", special: ["麵茶", "扭結麵包", "愛心扭結麵包"] },
    "Gabia": { super: "肉桂口味健康糖球", special: ["肉桂口味糖球", "檸檬茶", "有機檸檬茶"] },
    "Haley": { super: "一碗糯米飯", special: ["一碗米飯", "檸檬茶", "有機檸檬茶"] },
    "Hilde": { super: "皇家蜂蜜大蒜鮭魚", special: ["蜂蜜大蒜鮭魚", "太空食品", "ANSA太空食品"] },
    "Ifrit": { super: "軟軟焦糖布丁", special: ["焦糖布丁", "龍族糖果", "龍族氣死你糖果"] },
    "Jade": { super: "薄荷巧克力冰淇淋", special: ["巧克力冰淇淋", "龍族糖果", "龍族氣死你糖果"] },
    "Jubee": { super: "甜甜蜂蜜罐", special: ["蜂蜜罐", "棉花糖馬卡龍", "低糖棉花糖馬卡龍"] },
    "Kidian": { super: "愛心扭結麵包", special: ["扭結麵包", "獸糧罐頭", "高級獸糧罐頭"] },
    "Kommy": { super: "高級獸糧罐頭", special: ["獸糧罐頭", "焦糖爆米花", "追劇焦糖爆米花"] },
    "Kyarot": { super: "兩口草生菜包", special: ["一口草生菜包", "蜂蜜罐", "甜甜蜂蜜罐"] },
    "Lazy": { super: "高級獸糧罐頭", special: ["獸糧罐頭", "溫熱的冰美式咖啡", "滾燙的冰美式咖啡"] },
    "Leets": { super: "龍族氣死你糖果", special: ["龍族糖果", "空氣炸豬排", "氫氣炸豬排"] },
    "Levi": { super: "追劇焦糖爆米花", special: ["焦糖爆米花", "UFC炸胡蘿蔔", "UFC炸蔬菜"] },
    "MaestroMK2": { super: "石榴甜茶", special: ["石榴果實", "祕密葡萄汁", "一級祕密葡萄汁"] },
    "Mago": { super: "ANSA太空食品", special: ["太空食品", "獸糧罐頭", "高級獸糧罐頭"] },
    "Maison": "無",
    "Marie": { super: "UFC炸蔬菜", special: ["UFC炸胡蘿蔔", "焦糖布丁", "軟軟焦糖布丁"] },
    "Mayo": { super: "一級祕密葡萄汁", special: ["祕密葡萄汁", "一碗米飯", "一碗糯米飯"] },
    "Meluna": { super: "麝香甜瓜博孔奇尼起司", special: ["哈密瓜博孔奇尼起司", "一口草生菜包", "兩口草生菜包"] },
    "Momo": { super: "甜甜蜂蜜罐", special: ["蜂蜜罐", "空氣炸豬排", "氫氣炸豬排"] },
    "Mynx": "無",
    "Naia": { super: "夏威夷海藻蓋飯", special: ["海藻沙拉", "金糖葫蘆", "白金糖葫蘆"] },
    "Ner": { super: "低糖棉花糖馬卡龍", special: ["棉花糖馬卡龍", "哈密瓜博孔奇尼起司", "麝香甜瓜博孔奇尼起司"] },
    "Patula": "無",
    "Picora": { super: "白金糖葫蘆", special: ["金糖葫蘆", "溫熱的冰美式咖啡", "滾燙的冰美式咖啡"] },
    "Posher": { super: "椰子萬能青汁", special: ["椰子松針粥", "太空食品", "ANSA太空食品"] },
    "RenewaAwaken": { super: "有機檸檬茶", special: ["檸檬茶", "太空食品", "ANSA太空食品"] },
    "Rim": { super: "燉南瓜", special: ["南瓜濃湯", "祕密葡萄汁", "一級祕密葡萄汁"] },
    "Risty": { super: "石榴甜茶", special: ["石榴果實", "溫熱的冰美式咖啡", "滾燙的冰美式咖啡"] },
    "Rohne": { super: "白金糖葫蘆", special: ["金糖葫蘆", "巧克力冰淇淋", "深黑巧克力冰淇淋"] },
    "Rude": { super: "927穀麵茶", special: ["麵茶", "太空食品", "ANSA太空食品"] },
    "Rufo": { super: "皇家蜂蜜大蒜鮭魚", special: ["蜂蜜大蒜鮭魚", "哈密瓜博孔奇尼起司", "麝香甜瓜博孔奇尼起司"] },
    "Sari": { super: "皇家蜂蜜大蒜鮭魚", special: ["蜂蜜大蒜鮭魚", "焦糖布丁", "軟軟焦糖布丁"] },
    "Selline": { super: "惡靈布丁", special: ["幽靈布丁", "祕密葡萄汁", "一級祕密葡萄汁"] },
    "Shady": { super: "惡靈布丁", special: ["幽靈布丁", "石榴果實", "石榴甜茶"] },
    "Shoupan": { super: "ANSA太空食品", special: ["太空食品", "巧克力冰淇淋", "深黑巧克力冰淇淋"] },
    "Silphir": { super: "白金糖葫蘆", special: ["金糖葫蘆", "幽靈布丁", "惡靈布丁"] },
    "Sist": { super: "麝香甜瓜博孔奇尼起司", special: ["哈密瓜博孔奇尼起司", "溫熱的冰美式咖啡", "滾燙的冰美式咖啡"] },
    "Snorky": { super: "一碗糯米飯", special: ["一碗米飯", "麵茶", "927穀麵茶"] },
    "Speaki": { super: "肉桂口味健康糖球", special: ["肉桂口味糖球", "石榴果實", "石榴甜茶"] },
    "Sylla": { super: "氫氣炸豬排", special: ["空氣炸豬排", "蜂蜜罐", "甜甜蜂蜜罐"] },
    "Taida": { super: "滾燙的冰美式咖啡", special: ["溫熱的冰美式咖啡", "金糖葫蘆", "白金糖葫蘆"] },
    "Ui": { super: "夏威夷海藻蓋飯", special: ["海藻沙拉", "烤漫畫肉", "烤海賊漫畫肉"] },
    "Velvet": { super: "兩口草生菜包", special: ["一口草生菜包", "椰子松針粥", "椰子萬能青汁"] },
    "Veroo": "無",
    "Vivi": { super: "滾燙的冰美式咖啡", special: ["溫熱的冰美式咖啡", "肉桂口味糖球", "肉桂口味健康糖球"] },
    "xXionx": { super: "深黑巧克力冰淇淋", special: ["巧克力冰淇淋", "祕密葡萄汁", "一級祕密葡萄汁"] },
    "Yomi": { super: "燉南瓜", special: ["南瓜濃湯", "一口草生菜包", "兩口草生菜包"] },
    "Yumimi": { super: "兩口草生菜包", special: ["一口草生菜包", "太空食品", "ANSA太空食品"] }
};

const REWARD_MAP = {
    "Alice": ["細膩的鐵粉", "尖銳的針", "閃亮的玻璃"],
    "Allet": ["軟棉棉的樹木", "堅硬的石頭", "牛肉"],
    "Amelia": ["眨眼墨水", "可彎曲金屬", "濕潤的紙漿"],
    "Ashur": ["魚", "巧克力", "槭樹樹液"],
    "Aya": ["水果", "魚", "樹葉"],
    "Belita": ["起司", "寶石碎片", "麵粉"],
    "Beni": ["閃亮的玻璃", "寶石碎片", "魚"],
    "BigWood": ["眨眼墨水", "米", "濕潤的紙漿"],
    "Blanchet": ["濕潤的紙漿", "雞蛋", "回收塑膠"],
    "Butter": ["堅硬的石頭", "麵粉", "細膩的鐵粉"],
    "Canna": ["雞蛋", "起司", "睡眠眼罩"],
    "Carren": ["各式穀物", "堅硬的石頭", "雞蛋"],
    "Chloe": ["麵粉", "柔軟的棉花", "巧克力"],
    "Chopi": ["巧克力", "軟棉棉的樹木", "巧克力米"],
    "Cuee": [],
    "Diana": ["家禽肉", "起司", "尖銳的針"],
    "Ed": ["槭樹樹液", "濕潤的紙漿", "蜂蜜"],
    "Elena": ["尖銳的針", "家禽肉", "皮革樹葉"],
    "Epica": ["牛奶", "巧克力米", "眨眼墨水"],
    "Erpin": ["堅硬的碎布", "樹葉", "糖"],
    "Espi": ["皮革樹葉", "軟棉棉的樹木", "可彎曲金屬"],
    "Festa": ["巧克力", "堅硬的石頭", "巧克力米"],
    "Fricle": ["柔軟的棉花", "牛肉", "堅硬的碎布"],
    "Gabia": ["米", "牛肉", "百老師萬能醬料"],
    "Haley": ["細膩的鐵粉", "軟棉棉的樹木", "閃亮的玻璃"],
    "Hilde": ["可彎曲金屬", "魚", "軟棉棉的樹木"],
    "Ifrit": ["銅湯匙", "蔬菜", "堅硬的黑色果實"],
    "Jade": ["堅硬的黑色果實", "各式穀物", "水果"],
    "Jubee": ["軟棉棉的樹木", "濕潤的紙漿", "牛肉"],
    "Kidian": ["可彎曲金屬", "彩虹花汁", "軟棉棉的樹木"],
    "Kommy": ["酥脆的金箔", "堅硬的黑色果實", "起司"],
    "Kyarot": ["寶石碎片", "黏膩的黏土", "酥脆的金箔"],
    "Lazy": ["堅硬的石頭", "雞蛋", "細膩的鐵粉"],
    "Leets": ["酥脆的金箔", "細膩的鐵粉", "起司"],
    "Levi": ["堅硬的碎布", "水果", "糖"],
    "MaestroMK2": ["牛肉", "尖銳的針", "銅湯匙"],
    "Mago": ["堅硬的石頭", "百老師萬能醬料", "細膩的鐵粉"],
    "Maison": [],
    "Marie": ["軟棉棉的樹木", "百老師萬能醬料", "牛肉"],
    "Mayo": ["軟棉棉的樹木", "蔬菜", "牛肉"],
    "Meluna": ["堅硬的石頭", "魚", "細膩的鐵粉"],
    "Momo": ["堅硬的石頭", "睡眠眼罩", "細膩的鐵粉"],
    "Mynx": [],
    "Naia": ["酥脆的金箔", "眨眼墨水", "蜂蜜"],
    "Ner": ["細膩的鐵粉", "可彎曲金屬", "閃亮的玻璃"],
    "Patula": [],
    "Picora": ["皮革樹葉", "巧克力", "可彎曲金屬"],
    "Posher": ["黏膩的黏土", "閃亮的玻璃", "柔軟的棉花"],
    "RenewaAwaken": ["各式穀物", "閃亮的玻璃", "雞蛋"],
    "Rim": ["黏膩的黏土", "軟棉棉的樹木", "柔軟的棉花"],
    "Risty": ["銅湯匙", "柔軟的棉花", "堅硬的黑色果實"],
    "Rohne": ["黏膩的黏土", "巧克力米", "柔軟的棉花"],
    "Rude": ["巧克力米", "彩虹花汁", "米"],
    "Rufo": ["細膩的鐵粉", "蜂蜜", "閃亮的玻璃"],
    "Sari": ["彩虹花汁", "回收塑膠", "黏膩的黏土"],
    "Selline": ["糖", "皮革樹葉", "堅硬的石頭"],
    "Shady": ["黏膩的黏土", "槭樹樹液", "柔軟的棉花"],
    "Shoupan": ["濕潤的紙漿", "各式穀物", "回收塑膠"],
    "Silphir": ["百老師萬能醬料", "牛奶"],
    "Sist": ["睡眠眼罩", "水果", "家禽肉"],
    "Snorky": ["回收塑膠", "百老師萬能醬料", "彩虹花汁"],
    "Speaki": ["回收塑膠", "牛奶", "彩虹花汁"],
    "Sylla": ["軟棉棉的樹木", "蜂蜜", "牛肉"],
    "Taida": ["蜂蜜", "糖", "軟棉棉的樹木", "睡眠眼罩", "蔬菜"],
    "Ui": ["蔬菜", "麵粉", "各式穀物"],
    "Velvet": ["堅硬的石頭", "眨眼墨水", "細膩的鐵粉"],
    "Veroo": [],
    "Vivi": ["濕潤的紙漿", "蔬菜", "回收塑膠"],
    "xXionx": ["樹葉", "雞蛋", "寶石碎片"],
    "Yomi": ["睡眠眼罩", "酥脆的金箔", "家禽肉"],
    "Yumimi": ["麵粉", "銅湯匙", "巧克力"]
};

// ------------------------------------------
// 3. 圖標與圖片對應表
// ------------------------------------------
const LOBBY_BACKGROUNDS = [
    "https://firebasestorage.googleapis.com/v0/b/crayon-note.firebasestorage.app/o/lobby%2FLobby-100010-1.webp?alt=media&token=91171715-07aa-4c3d-aee6-0daf8099536c", "https://firebasestorage.googleapis.com/v0/b/crayon-note.firebasestorage.app/o/lobby%2FLobby-10002-1.webp?alt=media&token=e44c4eba-f9b0-4e1e-bd2c-bbcd5891be84", "https://firebasestorage.googleapis.com/v0/b/crayon-note.firebasestorage.app/o/lobby%2FLobby-10003-1.webp?alt=media&token=11071be4-520c-4bd4-ae9d-10aae72e6dd1",
    "https://firebasestorage.googleapis.com/v0/b/crayon-note.firebasestorage.app/o/lobby%2FLobby-10007-1.webp?alt=media&token=d5e8d59e-8dc0-41af-a18b-ed5e62a7cff2", "https://firebasestorage.googleapis.com/v0/b/crayon-note.firebasestorage.app/o/lobby%2FLobby-10008-1.webp?alt=media&token=daba6fe4-8708-4767-896f-e40867e86a2f", "https://firebasestorage.googleapis.com/v0/b/crayon-note.firebasestorage.app/o/lobby%2FLobby-10009-1.webp?alt=media&token=153f26aa-b336-4301-bffa-130172c0af75", "https://firebasestorage.googleapis.com/v0/b/crayon-note.firebasestorage.app/o/lobby%2FLobby_10001_1.webp?alt=media&token=97f5b368-2818-46f7-a957-6af54f9e3d33"
];
const ICON_MAP = {
    "personality_天真": "https://firebasestorage.googleapis.com/v0/b/crayon-note.firebasestorage.app/o/personality%2FPickUpPersonality_Naive.webp?alt=media&token=5439c0fb-4c8e-4097-a868-5534180db07f", "personality_活潑": "https://firebasestorage.googleapis.com/v0/b/crayon-note.firebasestorage.app/o/personality%2FPickUpPersonality_Jolly.webp?alt=media&token=701ad789-557c-4de7-ac4d-fc42e6b82cfb", "personality_冷靜": "https://firebasestorage.googleapis.com/v0/b/crayon-note.firebasestorage.app/o/personality%2FPickUpPersonality_Cool.webp?alt=media&token=d93be2cb-d36b-4923-badd-5c16557cb844", "personality_狂亂": "https://firebasestorage.googleapis.com/v0/b/crayon-note.firebasestorage.app/o/personality%2FPickUpPersonality_Mad.webp?alt=media&token=47f62ae9-38a3-489d-92fc-f034b6249cbe", "personality_憂鬱": "https://firebasestorage.googleapis.com/v0/b/crayon-note.firebasestorage.app/o/personality%2FPickUpPersonality_Gloomy.webp?alt=media&token=e22b91ef-4364-4055-986b-bad568c484c2",
    "race_精靈": "https://firebasestorage.googleapis.com/v0/b/crayon-note.firebasestorage.app/o/race%2Fjing-ling.webp?alt=media&token=4d4e6dff-b29c-42ea-a99c-231dd74a8d2c", "race_龍族": "https://firebasestorage.googleapis.com/v0/b/crayon-note.firebasestorage.app/o/race%2Flong-zu.webp?alt=media&token=9045bd8a-fd98-412c-a0ef-2fb57678776d", "race_妖精": "https://firebasestorage.googleapis.com/v0/b/crayon-note.firebasestorage.app/o/race%2Fyao-jing.webp?alt=media&token=02063405-85bd-48d5-91c3-5581a9e331a2", "race_魔靈": "https://firebasestorage.googleapis.com/v0/b/crayon-note.firebasestorage.app/o/race%2Fmo-ling.webp?alt=media&token=e7d63700-cfbe-4c98-8ea5-57ff4bdbe413", "race_獸人": "https://firebasestorage.googleapis.com/v0/b/crayon-note.firebasestorage.app/o/race%2Fshou-ren.webp?alt=media&token=dc1ffcdc-3cc6-4e0c-802b-b84cf3880415", "race_幽靈": "https://firebasestorage.googleapis.com/v0/b/crayon-note.firebasestorage.app/o/race%2Fyou-ling.webp?alt=media&token=5a07255e-9cc2-4a6e-9b66-9c828cba31c3", "race_魔女": "https://firebasestorage.googleapis.com/v0/b/crayon-note.firebasestorage.app/o/race%2Fmo-nu.webp?alt=media&token=f35ec5cd-7f58-4c98-9057-198160095847", "race_???": "https://firebasestorage.googleapis.com/v0/b/crayon-note.firebasestorage.app/o/race%2Funknown.webp?alt=media&token=ce9dc20a-eb6c-4030-aa4f-d685ce01b7ee",
    "position_前排": "https://firebasestorage.googleapis.com/v0/b/crayon-note.firebasestorage.app/o/position%2Fqian-pai.webp?alt=media&token=2d783ffa-a9d0-439a-ad9b-6312dd5b7917", "position_中排": "https://firebasestorage.googleapis.com/v0/b/crayon-note.firebasestorage.app/o/position%2Fzhong-pai.webp?alt=media&token=80552f69-ee52-48d7-a6b4-9c46e01f545d", "position_後排": "https://firebasestorage.googleapis.com/v0/b/crayon-note.firebasestorage.app/o/position%2Fhou-pai.webp?alt=media&token=8a03dca6-bc7f-443d-a0f1-1a193c91e7da",
    "job_肉盾": "https://firebasestorage.googleapis.com/v0/b/crayon-note.firebasestorage.app/o/job%2Frou-dun.webp?alt=media&token=168d2a45-3f81-4deb-a47b-f750404d2428", "job_輔助": "https://firebasestorage.googleapis.com/v0/b/crayon-note.firebasestorage.app/o/job%2Ffu-zhu.webp?alt=media&token=8076d16b-716f-4216-bcd4-c1f9930dc1d3", "job_輸出": "https://firebasestorage.googleapis.com/v0/b/crayon-note.firebasestorage.app/o/job%2Fshu-chu.webp?alt=media&token=d7bcfc6c-c908-4e6c-86e4-967cc5ba92fe",
    "grade_3":"https://i.postimg.cc/sDqK3Vk3/3STAR.png", "grade_2":"https://i.postimg.cc/wTZF96Cx/2STAR.png", "grade_1":"https://i.postimg.cc/TYFQTRzd/1STAR.png"
};
const IMAGE_MAP = {
    "personality_天真": "https://firebasestorage.googleapis.com/v0/b/crayon-note.firebasestorage.app/o/personality%2FPickUpPersonality_Naive.webp?alt=media&token=5439c0fb-4c8e-4097-a868-5534180db07f", "personality_活潑": "https://firebasestorage.googleapis.com/v0/b/crayon-note.firebasestorage.app/o/personality%2FPickUpPersonality_Jolly.webp?alt=media&token=701ad789-557c-4de7-ac4d-fc42e6b82cfb", "personality_冷靜": "https://firebasestorage.googleapis.com/v0/b/crayon-note.firebasestorage.app/o/personality%2FPickUpPersonality_Cool.webp?alt=media&token=d93be2cb-d36b-4923-badd-5c16557cb844", "personality_狂亂": "https://firebasestorage.googleapis.com/v0/b/crayon-note.firebasestorage.app/o/personality%2FPickUpPersonality_Mad.webp?alt=media&token=47f62ae9-38a3-489d-92fc-f034b6249cbe", "personality_憂鬱": "https://firebasestorage.googleapis.com/v0/b/crayon-note.firebasestorage.app/o/personality%2FPickUpPersonality_Gloomy.webp?alt=media&token=e22b91ef-4364-4055-986b-bad568c484c2",
    "race_精靈": "https://firebasestorage.googleapis.com/v0/b/crayon-note.firebasestorage.app/o/race%2Fjing-ling.webp?alt=media&token=4d4e6dff-b29c-42ea-a99c-231dd74a8d2c", "race_龍族": "https://firebasestorage.googleapis.com/v0/b/crayon-note.firebasestorage.app/o/race%2Flong-zu.webp?alt=media&token=9045bd8a-fd98-412c-a0ef-2fb57678776d", "race_妖精": "https://firebasestorage.googleapis.com/v0/b/crayon-note.firebasestorage.app/o/race%2Fyao-jing.webp?alt=media&token=02063405-85bd-48d5-91c3-5581a9e331a2", "race_魔靈": "https://firebasestorage.googleapis.com/v0/b/crayon-note.firebasestorage.app/o/race%2Fmo-ling.webp?alt=media&token=e7d63700-cfbe-4c98-8ea5-57ff4bdbe413", "race_獸人": "https://firebasestorage.googleapis.com/v0/b/crayon-note.firebasestorage.app/o/race%2Fshou-ren.webp?alt=media&token=dc1ffcdc-3cc6-4e0c-802b-b84cf3880415", "race_幽靈": "https://firebasestorage.googleapis.com/v0/b/crayon-note.firebasestorage.app/o/race%2Fyou-ling.webp?alt=media&token=5a07255e-9cc2-4a6e-9b66-9c828cba31c3", "race_魔女": "https://firebasestorage.googleapis.com/v0/b/crayon-note.firebasestorage.app/o/race%2Fmo-nu.webp?alt=media&token=f35ec5cd-7f58-4c98-9057-198160095847", "race_unknown": "https://firebasestorage.googleapis.com/v0/b/crayon-note.firebasestorage.app/o/race%2Funknown.webp?alt=media&token=ce9dc20a-eb6c-4030-aa4f-d685ce01b7ee",
    "position_前排": "https://firebasestorage.googleapis.com/v0/b/crayon-note.firebasestorage.app/o/position%2Fqian-pai.webp?alt=media&token=2d783ffa-a9d0-439a-ad9b-6312dd5b7917", "position_中排": "https://firebasestorage.googleapis.com/v0/b/crayon-note.firebasestorage.app/o/position%2Fzhong-pai.webp?alt=media&token=80552f69-ee52-48d7-a6b4-9c46e01f545d", "position_後排": "https://firebasestorage.googleapis.com/v0/b/crayon-note.firebasestorage.app/o/position%2Fhou-pai.webp?alt=media&token=8a03dca6-bc7f-443d-a0f1-1a193c91e7da",
    "job_肉盾": "https://firebasestorage.googleapis.com/v0/b/crayon-note.firebasestorage.app/o/job%2Frou-dun.webp?alt=media&token=168d2a45-3f81-4deb-a47b-f750404d2428", "job_輔助": "https://firebasestorage.googleapis.com/v0/b/crayon-note.firebasestorage.app/o/job%2Ffu-zhu.webp?alt=media&token=8076d16b-716f-4216-bcd4-c1f9930dc1d3", "job_輸出": "https://firebasestorage.googleapis.com/v0/b/crayon-note.firebasestorage.app/o/job%2Fshu-chu.webp?alt=media&token=d7bcfc6c-c908-4e6c-86e4-967cc5ba92fe",
    "hover_avatar_伊弗利特": "https://i.postimg.cc/zVmkt7qp/yi-fu-li-te2.png", "hover_avatar_伊德": "https://i.postimg.cc/6yshjcB0/yi-de2.png", "hover_avatar_佩佩": "https://i.postimg.cc/jLz4Gf5V/pei-pei2.png", "hover_avatar_佩斯塔": "https://i.postimg.cc/HVQ9fMLf/pei-si-ta2.png", "hover_avatar_修帕": "https://i.postimg.cc/XpwkT5JV/xiu-pa2.png", "hover_avatar_傑德": "https://i.postimg.cc/qN4x07h8/jie-de2.png", "hover_avatar_優米": "https://i.postimg.cc/fVCjbhY4/you-mi2.png", "hover_avatar_劉美美": "https://i.postimg.cc/G4KJp1Gf/liu-mei-mei2.png", "hover_avatar_加薇雅": "https://i.postimg.cc/7fvNs9q5/jia-wei-ya2.png", "hover_avatar_卡洛特": "https://i.postimg.cc/w7Kkf29t/ka-luo-te2.png", "hover_avatar_卡蓮": "https://i.postimg.cc/JGwQ6xRZ/ka-lian2.png", "hover_avatar_喬菲": "https://i.postimg.cc/5XbS1tYB/qiao-fei2.png", "hover_avatar_基狄恩": "https://i.postimg.cc/WdTwj4F3/ji-di-en2.png", "hover_avatar_大師2號": "https://i.postimg.cc/hfF0ysKz/da-shi2hao2.png", "hover_avatar_大木頭": "https://i.postimg.cc/svFJ6m3G/da-mu-tou2.png", "hover_avatar_奈雅": "https://i.postimg.cc/hf91HmGk/nai-ya2.png", "hover_avatar_奶油": "https://i.postimg.cc/XpMgHLnK/nai-you2.png", "hover_avatar_寧琉": "https://i.postimg.cc/hXsbGqT2/ning-liu2.png", "hover_avatar_布蘭切": "https://i.postimg.cc/QHLq4mjc/bu-lan-qie2.png", "hover_avatar_希拉": "https://i.postimg.cc/VdjW3tND/xi-la2.png", "hover_avatar_希爾德": "https://i.postimg.cc/tYhNL6gm/xi-er-de2.png", "hover_avatar_希瑟圖": "https://i.postimg.cc/PPmQBDqV/xi-se-tu2.png", "hover_avatar_希菲爾": "https://i.postimg.cc/svp4tW26/xi-fei-er2.png", "hover_avatar_帕特拉": "https://i.postimg.cc/56wSZz0J/pa-te-la2.png", "hover_avatar_庫洛艾": "https://i.postimg.cc/RW4L906z/ku-luo-ai2.png", "hover_avatar_康娜": "https://i.postimg.cc/87NmDCJj/kang-na2.png", "hover_avatar_愛麗絲": "https://i.postimg.cc/Snd7KpC6/ai-li-si2.png", "hover_avatar_斑尼": "https://i.postimg.cc/jDcQjrPw/ban-ni2.png", "hover_avatar_斯皮奇": "https://i.postimg.cc/zy7Sf1KR/si-pi-qi2.png", "hover_avatar_斯諾奇": "https://i.postimg.cc/RWdQ0zKJ/si-nuo-qi2.png", "hover_avatar_柯米": "https://i.postimg.cc/N51kWXMQ/ke-mi2.png", "hover_avatar_桃桃": "https://i.postimg.cc/cv0BZJgS/tao-tao2.png", "hover_avatar_梅森": "https://i.postimg.cc/QFhJsM9F/mei-sen2.png", "hover_avatar_梅露娜": "https://i.postimg.cc/LJ23RsY1/mei-lu-na2.png", "hover_avatar_泰達": "https://i.postimg.cc/18srPznP/tai-da2.png", "hover_avatar_洛涅": "https://i.postimg.cc/N51kWXMj/lu-nie2.png", "hover_avatar_海莉": "https://i.postimg.cc/MnqmxGMz/hai-li2.png", "hover_avatar_珀榭": "https://i.postimg.cc/TprJZbwP/po-xie2.png", "hover_avatar_琳": "https://i.postimg.cc/xX5ydSMH/lin2.png", "hover_avatar_瑟琳娜": "https://i.postimg.cc/hXsbGqT8/se-lin-na2.png", "hover_avatar_瑪約": "https://i.postimg.cc/w12cBdL4/ma-yue2.png", "hover_avatar_瑪麗": "https://i.postimg.cc/pmCYdtz7/ma-li2.png", "hover_avatar_皮可菈": "https://i.postimg.cc/tY0zSk9N/pi-ke-la2.png", "hover_avatar_盧波": "https://i.postimg.cc/zy7Sf1K9/lu-bo2.png", "hover_avatar_米雪": "https://i.postimg.cc/zVmkt7qd/mi-xue2.png", "hover_avatar_綾": "https://i.postimg.cc/68cLQNn1/ling2.png", "hover_avatar_羽伊": "https://i.postimg.cc/Czy4P7wP/yu-yi2.png", "hover_avatar_艾斯皮": "https://i.postimg.cc/nC81R2nw/ai-si-pi2.png", "hover_avatar_艾爾芬": "https://i.postimg.cc/rKSNv4pN/ai-er-fen2.png", "hover_avatar_艾琳娜": "https://i.postimg.cc/BXWCYpJV/ai-lin-na2.png", "hover_avatar_艾皮卡": "https://i.postimg.cc/rK69njqZ/ai-pi-ka2.png", "hover_avatar_艾舒爾": "https://i.postimg.cc/SJWfw9KG/ai-shu-er2.png", "hover_avatar_艾蜜莉雅": "https://i.postimg.cc/ZCrx1Nqw/ai-mi-li-ya2.png", "hover_avatar_芙莉可": "https://i.postimg.cc/crQBV3HS/fu-li-ke2.png", "hover_avatar_茱蜜": "https://i.postimg.cc/nXpGZLjH/zhu-mi2.png", "hover_avatar_莉茲": "https://i.postimg.cc/yDsyBNgg/li-zi2.png", "hover_avatar_莎莉": "https://i.postimg.cc/v4btMmg9/sha-li2.png", "hover_avatar_萊薇": "https://i.postimg.cc/K1frYyBB/lai-wei2.png", "hover_avatar_蒂亞娜": "https://i.postimg.cc/21GF5fhF/di-ya-na2.png", "hover_avatar_薇薇": "https://i.postimg.cc/w12cBdD8/wei-wei2.png", "hover_avatar_謝蒂": "https://i.postimg.cc/McG0Mrm9/xie-di2.png", "hover_avatar_貝魯": "https://i.postimg.cc/3dgFPGwc/bei-lu2.png", "hover_avatar_貝麗塔": "https://i.postimg.cc/QHpJR7Mv/bei-li-ta2.png", "hover_avatar_路德": "https://i.postimg.cc/hXsbGqTr/lu-de2.png", "hover_avatar_路易": "https://i.postimg.cc/TK0qPXgc/lu-yi2.png", "hover_avatar_錫安": "https://i.postimg.cc/sMm92R7k/xi-an2.png", "hover_avatar_阿萊特": "https://i.postimg.cc/crQBV3HZ/a-lai-te2.png", "hover_avatar_雷吉": "https://i.postimg.cc/Wd864PgS/lei-ji2.png", "hover_avatar_馬爾": "https://i.postimg.cc/pmRJxdhd/ma-er2.png", "hover_avatar_莉絲蒂": "https://i.postimg.cc/hhmFm0T6/li-si-di2.png", "hover_avatar_雷內瓦": "https://i.postimg.cc/kVcs6SpW/lei-nei-wa2.png",
    "avatar_洛涅": "https://i.postimg.cc/FkJWmkLf/Rohne.png", "avatar_薇薇": "https://i.postimg.cc/7bwsCbyJ/Vivi.png", "avatar_艾爾芬":"https://i.postimg.cc/WdcKN8S2/Erpin.png", "avatar_錫安": "https://i.postimg.cc/rDTnXmFV/x-Xionx.png", "avatar_伊弗利特": "https://i.postimg.cc/SnLPJ9tC/Ifrit.png", "avatar_伊德": "https://i.postimg.cc/XpCm6mKn/Ed.png", "avatar_佩佩": "https://i.postimg.cc/BXHYVDsb/Velvet.png", "avatar_佩斯塔": "https://i.postimg.cc/Snb5SdVs/Festa.png", "avatar_修帕": "https://i.postimg.cc/t71mFwM3/Shoupan.png", "avatar_傑德": "https://i.postimg.cc/CRC2z864/Jade.png", "avatar_優米": "https://i.postimg.cc/K4xqK4yK/Yomi.png", "avatar_劉美美": "https://i.postimg.cc/kDq1VDdB/Yumimi.png", "avatar_加薇雅": "https://i.postimg.cc/yDC51jnh/Gabia.png", "avatar_卡洛特": "https://i.postimg.cc/Y4psgSJs/Kyarot.png", "avatar_卡蓮": "https://i.postimg.cc/4nMqMs9p/Carren.png", "avatar_喬菲": "https://i.postimg.cc/Rq8y84HP/Chopi.png", "avatar_基狄恩": "https://i.postimg.cc/DSQN8GYM/Kidian.png", "avatar_大師2號": "https://i.postimg.cc/DW2Msz9S/Maestro-MK2.png", "avatar_大木頭": "https://i.postimg.cc/G9NVNdyH/Big-Wood.png", "avatar_奈雅": "https://i.postimg.cc/njrSRPVB/Naia.png", "avatar_奶油": "https://i.postimg.cc/hhw6wcdJ/Butter.png", "avatar_布蘭切": "https://i.postimg.cc/qgYSY437/Blanchet.png", "avatar_希拉": "https://i.postimg.cc/vcfqN9y2/Sylla.png", "avatar_希爾德": "https://i.postimg.cc/ZWPQCNDd/Hilde.png", "avatar_希瑟圖": "https://i.postimg.cc/14L7BBkH/Sist.png", "avatar_希菲爾": "https://i.postimg.cc/8sqX442W/Silphir.png", "avatar_帕特拉": "https://i.postimg.cc/XGq1HzNt/Patula.png", "avatar_庫洛艾": "https://i.postimg.cc/Z0g2g4dV/Chloe.png", "avatar_康娜": "https://i.postimg.cc/9zSKSC7P/Canna.png", "avatar_愛麗絲": "https://i.postimg.cc/YL4V9yJ3/Alice.png", "avatar_斑尼": "https://i.postimg.cc/SjjHDJJX/Beni.png", "avatar_斯皮奇": "https://i.postimg.cc/Dmtp669j/Speaki.png", "avatar_斯諾奇": "https://i.postimg.cc/PNBVyygS/Snorky.png", "avatar_柯米": "https://i.postimg.cc/dhRfLCSS/Kommy.png", "avatar_桃桃": "https://i.postimg.cc/GBqSjCRx/Momo.png", "avatar_梅森": "https://i.postimg.cc/Z9VDLSm4/Maison.png", "avatar_梅露娜": "https://i.postimg.cc/3ynbZThX/Meluna.png", "avatar_海莉": "https://i.postimg.cc/w15r7Nby/Haley.png", "avatar_珀榭": "https://i.postimg.cc/xJZxW3qw/Posher.png", "avatar_琳": "https://i.postimg.cc/tnVSynx4/Rim.png", "avatar_瑟琳娜": "https://i.postimg.cc/Bt8w2kV4/Selline.png", "avatar_瑪約": "https://i.postimg.cc/d74S9YFk/Mayo.png", "avatar_瑪麗": "https://i.postimg.cc/XZQDgbWB/Marie.png", "avatar_皮可菈": "https://i.postimg.cc/34NfScJH/Picora.png", "avatar_盧波": "https://i.postimg.cc/JHB6mHkq/Rufo.png", "avatar_米雪": "https://i.postimg.cc/VSDHF8wR/Mynx.png", "avatar_綾": "https://i.postimg.cc/fkk1BJJQ/Aya.png", "avatar_羽伊":"https://i.postimg.cc/N5mJzTtW/Ui.png", "avatar_艾斯皮": "https://i.postimg.cc/RWx8SdGv/Espi.png", "avatar_艾琳娜": "https://i.postimg.cc/KRMwhw7G/Elena.png", "avatar_艾皮卡": "https://i.postimg.cc/9DHSmb12/Epica.png", "avatar_艾舒爾": "https://i.postimg.cc/pyy3qpyw/Ashur.png", "avatar_艾蜜莉雅": "https://i.postimg.cc/xNk7CFWy/Amelia.png", "avatar_芙莉可": "https://i.postimg.cc/JsCgrxKD/Fricle.png", "avatar_茱蜜": "https://i.postimg.cc/WdmyhZf8/Jubee.png", "avatar_莉茲": "https://i.postimg.cc/LqHbfscR/Leets.png", "avatar_莎莉": "https://i.postimg.cc/c6K5f2bS/Sari.png", "avatar_萊薇": "https://i.postimg.cc/McWFRGCS/Levi.png", "avatar_蒂亞娜": "https://i.postimg.cc/3dvVQVj5/Diana.png", "avatar_謝蒂": "https://i.postimg.cc/c6K5f2bx/Shady.png", "avatar_貝魯": "https://i.postimg.cc/2VhcKvm5/Veroo.png", "avatar_貝麗塔": "https://i.postimg.cc/xqqBtccJ/Belita.png", "avatar_路德": "https://i.postimg.cc/JHB6mHkT/Rude.png", "avatar_路易": "https://i.postimg.cc/D8XH3Hr5/Cuee.png", "avatar_阿萊特": "https://i.postimg.cc/QKBPtnRg/Allet.png", "avatar_雷吉": "https://i.postimg.cc/rd8PWpvb/Lazy.png", "avatar_馬爾": "https://i.postimg.cc/gwYTR0Cw/Mago.png", "avatar_泰達": "https://i.postimg.cc/5jZKgpcc/Taida.png", "avatar_寧琉": "https://i.postimg.cc/YG0Dns26/Ner.png", "avatar_莉絲蒂": "https://i.postimg.cc/5QF71QCX/Risty.png", "avatar_雷內瓦": "https://i.postimg.cc/5Yr7ZS6j/Renewa-Awaken.png"
	//新角色備用https://i.postimg.cc/SYX5stwd/Arco.png, https://i.postimg.cc/mhhK8th0/Arnet.png, https://i.postimg.cc/pyy3qppt/Bana.png, https://i.postimg.cc/grr1Nnn0/Barie.png, https://i.postimg.cc/5jjDn66y/Barong.png, https://i.postimg.cc/YjVZVMWj/Beni-Beni.png, https://i.postimg.cc/0r3F3PwD/Canta.png, https://i.postimg.cc/RNHyxy7P/Crepe.png, https://i.postimg.cc/kBbzPzQz/Daya.png, https://i.postimg.cc/mtHJWJYn/Delia.png, https://i.postimg.cc/Ln1wFwkd/Diana-Yester.png, https://i.postimg.cc/ykZtCth6/Eisia.png, https://i.postimg.cc/NKvVsDb1/Goldy.png, https://i.postimg.cc/JsCgrxKc/Guin.png, https://i.postimg.cc/87dYjvnZ/Joanne.png, https://i.postimg.cc/w15r7NG8/Kommy-Swim.png, https://i.postimg.cc/5HxRvtZT/Laika.png, https://i.postimg.cc/R3MDf0kz/Lethe.png, https://i.postimg.cc/B8qVDvr4/Lil1li.png, https://i.postimg.cc/B8qVDvrb/Lion.png, https://i.postimg.cc/xktFP2Qk/Makasha.png, https://i.postimg.cc/7CmQNk4S/Mayo-Cool.png, https://i.postimg.cc/JD0Y6273/Neti.png, https://i.postimg.cc/DJ0pjMf5/Opal.png, https://i.postimg.cc/DJ0pjMfM/Orr.png, https://i.postimg.cc/phrcG6Xv/Pira.png, https://i.postimg.cc/vgKqptDC/Polan.png, https://i.postimg.cc/ygGQwykK/Ran.png, https://i.postimg.cc/phSGgJpT/Renewa.png, https://i.postimg.cc/470LrQmy/Ricota.png, https://i.postimg.cc/5QF71QC6/Rim-Chaos.png, https://i.postimg.cc/V0bG10Cn/Rohne-Mayor.png, https://i.postimg.cc/D4bjF4Xd/Rollett.png, https://i.postimg.cc/3Wyb2Vcw/Shady-Twisted.png, https://i.postimg.cc/7bCQSdWf/Shasha.png, https://i.postimg.cc/bdGF1WBk/Sherum.png, https://i.postimg.cc/RqjpddkP/Speaki-Maid.png, https://i.postimg.cc/4nr2PPDj/Suro.png, https://i.postimg.cc/kBK1p8CL/Tig.png, https://i.postimg.cc/rKxnPWcT/Uros.png, https://i.postimg.cc/JGZ62Jmm/Vela.png
};

const SKILL_ICONS = {
    "attack_物理": "https://i.postimg.cc/7Cng30rY/wu-li-gong-ji.png", "attack_魔法": "https://i.postimg.cc/Nyk16mvM/mo-fa-gong-ji.png",
    
    "skill_normal_伊弗利特": "https://i.postimg.cc/cgDH2ngX/yi-fu-li-te3.png", "skill_normal_伊德": "https://i.postimg.cc/njdzgDj3/yi-de3.png", "skill_normal_佩佩": "https://i.postimg.cc/MMsTNQf6/pei-pei3.png", "skill_normal_佩斯塔": "https://i.postimg.cc/478dq9H4/pei-si-ta3.png", "skill_normal_修帕": "https://i.postimg.cc/2LV6DSnj/xiu-pa3.png", "skill_normal_傑德": "https://i.postimg.cc/1VftQ3DG/jie-de3.png", "skill_normal_優米": "https://i.postimg.cc/z3B3W04G/you-mi3.png", "skill_normal_劉美美": "https://i.postimg.cc/vDBD93CG/liu-mei-mei3.png", "skill_normal_加薇雅": "https://i.postimg.cc/CBM5cN1c/jia-wei-ya3.png", "skill_normal_卡洛特": "https://i.postimg.cc/mzZkmwDd/ka-luo-te3.png", "skill_normal_卡蓮": "https://i.postimg.cc/34LRVv4F/ka-lian3.png", "skill_normal_喬菲": "https://i.postimg.cc/4Hmdgxpz/qiao-fei3.png", "skill_normal_基狄恩": "https://i.postimg.cc/D48ZTw1S/ji-di-en3.png", "skill_normal_大師2號": "https://i.postimg.cc/mzZkmwDN/da-shi2hao3.png", "skill_normal_大木頭": "https://i.postimg.cc/sQfxTcXP/da-mu-tou3.png", "skill_normal_奈雅": "https://i.postimg.cc/Cnz1gxbT/nai-ya3.png", "skill_normal_奶油": "https://i.postimg.cc/ZBYnwcRQ/nai-you3.png", "skill_normal_寧琉": "https://i.postimg.cc/2363v2gm/ning-liu3.png", "skill_normal_布蘭切": "https://i.postimg.cc/vgPBkVgX/bu-lan-qie3.png", "skill_normal_希拉": "https://i.postimg.cc/wyWvZmyC/xi-la3.png", "skill_normal_希爾德": "https://i.postimg.cc/njdzgD9p/xi-er-de3.png", "skill_normal_希瑟圖": "https://i.postimg.cc/dkW1pyZv/xi-se-tu3.png", "skill_normal_希菲爾": "https://i.postimg.cc/XG2JmCBb/xi-fei-er3.png", "skill_normal_帕特拉": "https://i.postimg.cc/5Q60V28M/pa-te-la3.png", "skill_normal_庫洛艾": "https://i.postimg.cc/4Hmdgxpx/ku-luo-ai3.png", "skill_normal_康娜": "https://i.postimg.cc/kRB4mgWR/kang-na3.png", "skill_normal_愛麗絲": "https://i.postimg.cc/yWdW9vtG/ai-li-si3.png", "skill_normal_斑尼": "https://i.postimg.cc/BPX60n25/ban-ni3.png", "skill_normal_斯皮奇": "https://i.postimg.cc/PvPxj51Q/si-pi-qi3.png", "skill_normal_斯諾奇": "https://i.postimg.cc/s1X1Swq6/si-nuo-qi3.png", "skill_normal_柯米": "https://i.postimg.cc/SYJshxcy/ke-mi3.png", "skill_normal_桃桃": "https://i.postimg.cc/rRKmkw5m/tao-tao3.png", "skill_normal_梅森": "https://i.postimg.cc/V0d68kXb/mei-sen3.png", "skill_normal_梅露娜": "https://i.postimg.cc/XBpJbY9C/mei-lu-na3.png", "skill_normal_泰達": "https://i.postimg.cc/K3Rz28tj/tai-da3.png", "skill_normal_洛涅": "https://i.postimg.cc/ZvCRS56J/luo-nie3.png", "skill_normal_海莉": "https://i.postimg.cc/wR7vpjD3/hai-li3.png", "skill_normal_珀榭": "https://i.postimg.cc/PvPxj51X/po-xie3.png", "skill_normal_琳": "https://i.postimg.cc/dD1Dd4pN/lin3.png", "skill_normal_瑟琳娜": "https://i.postimg.cc/Bt6tDMky/se-lin-na3.png", "skill_normal_瑪約": "https://i.postimg.cc/LhXhfNGS/ma-yue3.png", "skill_normal_瑪麗": "https://i.postimg.cc/3WRWpnzJ/ma-li3.png", "skill_normal_皮可菈": "https://i.postimg.cc/WF93CkF7/pi-ke-la.png", "skill_normal_盧波": "https://i.postimg.cc/rzmzWQ7y/lu-bo3.png", "skill_normal_米雪": "https://i.postimg.cc/9RxMK7RN/mi-xue3.png", "skill_normal_綾": "https://i.postimg.cc/7b6b7mjH/ling3.png", "skill_normal_羽伊": "https://i.postimg.cc/BLh6kKLY/yu-yi3.png", "skill_normal_艾斯皮": "https://i.postimg.cc/62H3gv2m/ai-si-pi3.png", "skill_normal_艾爾芬": "https://i.postimg.cc/wyWvZmyS/ai-er-fen3.png", "skill_normal_艾琳娜": "https://i.postimg.cc/34LRVv4q/ai-lin-na3.png", "skill_normal_艾皮卡": "https://i.postimg.cc/HcSxRycv/ai-pi-ka3.png", "skill_normal_艾舒爾": "https://i.postimg.cc/WF93CkFx/ai-shu-er3.png", "skill_normal_艾蜜莉雅": "https://i.postimg.cc/0MtQFwK1/ai-mi-li-ya3.png", "skill_normal_芙莉可": "https://i.postimg.cc/5Q60V28V/fu-li-ke3.png", "skill_normal_茱蜜": "https://i.postimg.cc/H8VxgkbV/zhu-mi3.png", "skill_normal_莉茲": "https://i.postimg.cc/RJNFBZwf/li-zi3.png", "skill_normal_莎莉": "https://i.postimg.cc/Wqh3v100/sha-li3.png", "skill_normal_萊薇": "https://i.postimg.cc/8s5sWt90/lai-wei3.png", "skill_normal_蒂亞娜": "https://i.postimg.cc/dD1Dd4pg/di-ya-na3.png", "skill_normal_薇薇": "https://i.postimg.cc/DmZmsBRm/wei-wei3.png", "skill_normal_謝蒂": "https://i.postimg.cc/jC5CNZBL/xie-di3.png", "skill_normal_貝魯": "https://i.postimg.cc/7GB6d2J4/bei-lu3.png", "skill_normal_貝麗塔": "https://i.postimg.cc/DJCZHX47/bei-li-ta3.png", "skill_normal_路德": "https://i.postimg.cc/t7T7P28G/lu-de3.png", "skill_normal_路易": "https://i.postimg.cc/Yj9jgbZ5/lu-yi3.png", "skill_normal_錫安": "https://i.postimg.cc/14t46Jb8/xi-an3.png", "skill_normal_阿萊特": "https://i.postimg.cc/XBpJbY93/a-lai-te3.png", "skill_normal_雷吉": "https://i.postimg.cc/dD1Dd4gP/lei-ji3.png", "skill_normal_馬爾": "https://i.postimg.cc/fSJLNRY3/ma-er3.png", "skill_normal_莉絲蒂": "https://i.postimg.cc/N2rqd6K7/li-si-di3.png", "skill_normal_雷內瓦": "https://i.postimg.cc/947VcW8s/lei-nei-wa3.png",
    
    "hover_avatar_伊弗利特": "https://i.postimg.cc/zVmkt7qp/yi-fu-li-te2.png", "hover_avatar_伊德": "https://i.postimg.cc/6yshjcB0/yi-de2.png", "hover_avatar_佩佩": "https://i.postimg.cc/jLz4Gf5V/pei-pei2.png", "hover_avatar_佩斯塔": "https://i.postimg.cc/HVQ9fMLf/pei-si-ta2.png", "hover_avatar_修帕": "https://i.postimg.cc/XpwkT5JV/xiu-pa2.png", "hover_avatar_傑德": "https://i.postimg.cc/qN4x07h8/jie-de2.png", "hover_avatar_優米": "https://i.postimg.cc/fVCjbhY4/you-mi2.png", "hover_avatar_劉美美": "https://i.postimg.cc/G4KJp1Gf/liu-mei-mei2.png", "hover_avatar_加薇雅": "https://i.postimg.cc/7fvNs9q5/jia-wei-ya2.png", "hover_avatar_卡洛特": "https://i.postimg.cc/w7Kkf29t/ka-luo-te2.png", "hover_avatar_卡蓮": "https://i.postimg.cc/JGwQ6xRZ/ka-lian2.png", "hover_avatar_喬菲": "https://i.postimg.cc/5XbS1tYB/qiao-fei2.png", "hover_avatar_基狄恩": "https://i.postimg.cc/WdTwj4F3/ji-di-en2.png", "hover_avatar_大師2號": "https://i.postimg.cc/hfF0ysKz/da-shi2hao2.png", "hover_avatar_大木頭": "https://i.postimg.cc/svFJ6m3G/da-mu-tou2.png", "hover_avatar_奈雅": "https://i.postimg.cc/hf91HmGk/nai-ya2.png", "hover_avatar_奶油": "https://i.postimg.cc/XpMgHLnK/nai-you2.png", "hover_avatar_寧琉": "https://i.postimg.cc/hXsbGqT2/ning-liu2.png", "hover_avatar_布蘭切": "https://i.postimg.cc/QHLq4mjc/bu-lan-qie2.png", "hover_avatar_希拉": "https://i.postimg.cc/VdjW3tND/xi-la2.png", "hover_avatar_希爾德": "https://i.postimg.cc/tYhNL6gm/xi-er-de2.png", "hover_avatar_希瑟圖": "https://i.postimg.cc/PPmQBDqV/xi-se-tu2.png", "hover_avatar_希菲爾": "https://i.postimg.cc/svp4tW26/xi-fei-er2.png", "hover_avatar_帕特拉": "https://i.postimg.cc/56wSZz0J/pa-te-la2.png", "hover_avatar_庫洛艾": "https://i.postimg.cc/RW4L906z/ku-luo-ai2.png", "hover_avatar_康娜": "https://i.postimg.cc/87NmDCJj/kang-na2.png", "hover_avatar_愛麗絲": "https://i.postimg.cc/Snd7KpC6/ai-li-si2.png", "hover_avatar_斑尼": "https://i.postimg.cc/jDcQjrPw/ban-ni2.png", "hover_avatar_斯皮奇": "https://i.postimg.cc/zy7Sf1KR/si-pi-qi2.png", "hover_avatar_斯諾奇": "https://i.postimg.cc/RWdQ0zKJ/si-nuo-qi2.png", "hover_avatar_柯米": "https://i.postimg.cc/N51kWXMQ/ke-mi2.png", "hover_avatar_桃桃": "https://i.postimg.cc/cv0BZJgS/tao-tao2.png", "hover_avatar_梅森": "https://i.postimg.cc/QFhJsM9F/mei-sen2.png", "hover_avatar_梅露娜": "https://i.postimg.cc/LJ23RsY1/mei-lu-na2.png", "hover_avatar_泰達": "https://i.postimg.cc/18srPznP/tai-da2.png", "hover_avatar_洛涅": "https://i.postimg.cc/N51kWXMj/lu-nie2.png", "hover_avatar_海莉": "https://i.postimg.cc/MnqmxGMz/hai-li2.png", "hover_avatar_珀榭": "https://i.postimg.cc/TprJZbwP/po-xie2.png", "hover_avatar_琳": "https://i.postimg.cc/xX5ydSMH/lin2.png", "hover_avatar_瑟琳娜": "https://i.postimg.cc/hXsbGqT8/se-lin-na2.png", "hover_avatar_瑪約": "https://i.postimg.cc/w12cBdL4/ma-yue2.png", "hover_avatar_瑪麗": "https://i.postimg.cc/pmCYdtz7/ma-li2.png", "hover_avatar_皮可菈": "https://i.postimg.cc/tY0zSk9N/pi-ke-la2.png", "hover_avatar_盧波": "https://i.postimg.cc/zy7Sf1K9/lu-bo2.png", "hover_avatar_米雪": "https://i.postimg.cc/zVmkt7qd/mi-xue2.png", "hover_avatar_綾": "https://i.postimg.cc/68cLQNn1/ling2.png", "hover_avatar_羽伊": "https://i.postimg.cc/Czy4P7wP/yu-yi2.png", "hover_avatar_艾斯皮": "https://i.postimg.cc/nC81R2nw/ai-si-pi2.png", "hover_avatar_艾爾芬": "https://i.postimg.cc/rKSNv4pN/ai-er-fen2.png", "hover_avatar_艾琳娜": "https://i.postimg.cc/BXWCYpJV/ai-lin-na2.png", "hover_avatar_艾皮卡": "https://i.postimg.cc/rK69njqZ/ai-pi-ka2.png", "hover_avatar_艾舒爾": "https://i.postimg.cc/SJWfw9KG/ai-shu-er2.png", "hover_avatar_艾蜜莉雅": "https://i.postimg.cc/ZCrx1Nqw/ai-mi-li-ya2.png", "hover_avatar_芙莉可": "https://i.postimg.cc/crQBV3HS/fu-li-ke2.png", "hover_avatar_茱蜜": "https://i.postimg.cc/nXpGZLjH/zhu-mi2.png", "hover_avatar_莉茲": "https://i.postimg.cc/yDsyBNgg/li-zi2.png", "hover_avatar_莎莉": "https://i.postimg.cc/v4btMmg9/sha-li2.png", "hover_avatar_萊薇": "https://i.postimg.cc/K1frYyBB/lai-wei2.png", "hover_avatar_蒂亞娜": "https://i.postimg.cc/21GF5fhF/di-ya-na2.png", "hover_avatar_薇薇": "https://i.postimg.cc/w12cBdD8/wei-wei2.png", "hover_avatar_謝蒂": "https://i.postimg.cc/McG0Mrm9/xie-di2.png", "hover_avatar_貝魯": "https://i.postimg.cc/3dgFPGwc/bei-lu2.png", "hover_avatar_貝麗塔": "https://i.postimg.cc/QHpJR7Mv/bei-li-ta2.png", "hover_avatar_路德": "https://i.postimg.cc/hXsbGqTr/lu-de2.png", "hover_avatar_路易": "https://i.postimg.cc/TK0qPXgc/lu-yi2.png", "hover_avatar_錫安": "https://i.postimg.cc/sMm92R7k/xi-an2.png", "hover_avatar_阿萊特": "https://i.postimg.cc/crQBV3HZ/a-lai-te2.png", "hover_avatar_雷吉": "https://i.postimg.cc/Wd864PgS/lei-ji2.png", "hover_avatar_馬爾": "https://i.postimg.cc/pmRJxdhd/ma-er2.png", "hover_avatar_莉絲蒂": "https://i.postimg.cc/hhmFm0T6/li-si-di2.png", "hover_avatar_雷內瓦": "https://i.postimg.cc/kVcs6SpW/lei-nei-wa2.png",
    
    "skill_passive_伊弗利特": "https://i.postimg.cc/wRKb1DXf/yi-fu-li-te4.png", "skill_passive_伊德": "https://i.postimg.cc/hQ9ZThs0/yi-de4.png", "skill_passive_佩佩": "https://i.postimg.cc/grRTfBpx/pei-pei4.png", "skill_passive_佩斯塔": "https://i.postimg.cc/jCNFGkTW/pei-si-ta4.png", "skill_passive_修帕": "https://i.postimg.cc/qgn59ZrZ/xiu-pa4.png", "skill_passive_傑德": "https://i.postimg.cc/ppH6xYXR/jie-de4.png", "skill_passive_優米": "https://i.postimg.cc/ykyrNgkX/you-mi4.png", "skill_passive_劉美美": "https://i.postimg.cc/vctSmgc6/liu-mei-mei4.png", "skill_passive_加薇雅": "https://i.postimg.cc/2LpX1nQ4/jia-wei-ya4.png", "skill_passive_卡洛特": "https://i.postimg.cc/D4VYS1rQ/ka-luo-te4.jpg", "skill_passive_卡蓮": "https://i.postimg.cc/RJrbWw7Q/ka-lian4.png", "skill_passive_喬菲": "https://i.postimg.cc/1fQjPc5S/qiao-fei4.png", "skill_passive_基狄恩": "https://i.postimg.cc/7fkWDMPt/ji-di-en4.png", "skill_passive_大師2號": "https://i.postimg.cc/GT0S4vFF/da-shi2hao4.png", "skill_passive_大木頭": "https://i.postimg.cc/XBMDr9fd/da-mu-tou4.png", "skill_passive_奈雅": "https://i.postimg.cc/grRTfBp6/nai-ya4.png", "skill_passive_奶油": "https://i.postimg.cc/30Mbk2XF/nai-you4.png", "skill_passive_寧琉": "https://i.postimg.cc/mty6rztr/ning-liu4.jpg", "skill_passive_布蘭切": "https://i.postimg.cc/bSXFZ1x3/bu-lan-qie4.png", "skill_passive_希拉": "https://i.postimg.cc/Cnjrkd7W/xi-la4.png", "skill_passive_希爾德": "https://i.postimg.cc/ctQkw6Td/xi-er-de4.png", "skill_passive_希瑟圖": "https://i.postimg.cc/tnhvW7Dj/xi-se-tu4.png", "skill_passive_希菲爾": "https://i.postimg.cc/vxW2fDXw/xi-fei-er4.png", "skill_passive_帕特拉": "https://i.postimg.cc/hhx5H3nQ/pa-te-la4.png", "skill_passive_庫洛艾": "https://i.postimg.cc/7b7WpQ4R/ku-luo-ai4.png", "skill_passive_康娜": "https://i.postimg.cc/BX0VscZV/kang-na4.png", "skill_passive_愛麗絲": "https://i.postimg.cc/MvSFxbKT/ai-li-si4.png", "skill_passive_斑尼": "https://i.postimg.cc/LnpbRB6R/ban-ni4.png", "skill_passive_斯皮奇": "https://i.postimg.cc/BX0VscQJ/si-pi-qi4.png", "skill_passive_斯諾奇": "https://i.postimg.cc/crSbZM4C/si-nuo-qi4.jpg", "skill_passive_柯米": "https://i.postimg.cc/Z03M1DmP/ke-mi4.png", "skill_passive_桃桃": "https://i.postimg.cc/w3JGSbzS/tao-tao4.png", "skill_passive_梅森": "https://i.postimg.cc/ppH6xYVg/mei-sen4.png", "skill_passive_梅露娜": "https://i.postimg.cc/crSbZM12/mei-lu-na4.png", "skill_passive_泰達": "https://i.postimg.cc/9zTnvN2S/tai-da4.png", "skill_passive_洛涅": "https://i.postimg.cc/Hj5hfPmt/luo-nie4.png", "skill_passive_海莉": "https://i.postimg.cc/RNBD9QCP/hai-li4.png", "skill_passive_珀榭": "https://i.postimg.cc/MXRFhrwt/po-xie4.png", "skill_passive_琳": "https://i.postimg.cc/PPQFqpPj/lin4.png", "skill_passive_瑟琳娜": "https://i.postimg.cc/YhzySGht/se-lin-na4.jpg", "skill_passive_瑪約": "https://i.postimg.cc/2V7X5bV6/ma-yue4.png", "skill_passive_瑪麗": "https://i.postimg.cc/xc3FdJcH/ma-li4.png", "skill_passive_皮可菈": "https://i.postimg.cc/1VxY8DGB/pi-ke-la4.png", "skill_passive_盧波": "https://i.postimg.cc/PPQFqpPY/lu-bo4.png", "skill_passive_米雪": "https://i.postimg.cc/5QwKLjg8/mi-xue4.png", "skill_passive_綾": "https://i.postimg.cc/ZCxDqBCB/ling4.png", "skill_passive_羽伊": "https://i.postimg.cc/sGpH71mw/yu-yi4.png", "skill_passive_艾斯皮": "https://i.postimg.cc/Zvrsp0Hw/ai-si-pi4.png", "skill_passive_艾爾芬": "https://i.postimg.cc/9wGgZzbS/ai-er-fen4.png", "skill_passive_艾琳娜": "https://i.postimg.cc/BPx7Htp7/ai-lin-na4.png", "skill_passive_艾皮卡": "https://i.postimg.cc/1Vp7w4BB/ai-pi-ka4.png", "skill_passive_艾舒爾": "https://i.postimg.cc/fSxqmkCg/ai-shu-er4.png", "skill_passive_艾蜜莉雅": "https://i.postimg.cc/YL1DYjRT/ai-mi-li-ya4.png", "skill_passive_芙莉可": "https://i.postimg.cc/3WpcPbhg/fu-li-ke4.png", "skill_passive_茱蜜": "https://i.postimg.cc/1fQjPcRB/zhu-mi4.png", "skill_passive_莉茲": "https://i.postimg.cc/bshB8HY7/li-zi4.png", "skill_passive_莎莉": "https://i.postimg.cc/RNBD9QV5/sha-li4.png", "skill_passive_萊薇": "https://i.postimg.cc/JGL2mc4h/lai-wei4.png", "skill_passive_蒂亞娜": "https://i.postimg.cc/gnHB0XnY/di-ya-na4.png", "skill_passive_薇薇": "https://i.postimg.cc/MnZ3f6Qj/wei-wei4.png", "skill_passive_謝蒂": "https://i.postimg.cc/pmVc5WFF/xie-di4.png", "skill_passive_貝魯": "https://i.postimg.cc/FkjC31GQ/bei-lu4.png", "skill_passive_貝麗塔": "https://i.postimg.cc/9wGgZz1W/bei-li-ta4.png", "skill_passive_路德": "https://i.postimg.cc/rKNYp0Kz/lu-de4.png", "skill_passive_路易": "https://i.postimg.cc/crB5Jgrx/lu-yi4.png", "skill_passive_錫安": "https://i.postimg.cc/dLjS0kLj/xi-an4.png", "skill_passive_阿萊特": "https://i.postimg.cc/YjgsJy7Y/a-lai-te4.png", "skill_passive_雷吉": "https://i.postimg.cc/MvmrGMvp/lei-ji4.png", "skill_passive_馬爾": "https://i.postimg.cc/6yXmwL6M/ma-er4.png", "skill_passive_莉絲蒂": "https://i.postimg.cc/YjVtQ9vT/li-si-di4.png", "skill_passive_雷內瓦": "https://i.postimg.cc/HJxHRwXc/lei-nei-wa4.png"
};

const FOOD_ICON = {
    "草莓蛋糕": { ja: "イチゴケーキ", url: "https://i.postimg.cc/ZWC1KYw9/Icon-Food-1.png" },
    "巧克力冰淇淋": { ja: "チョコアイス", url: "https://i.postimg.cc/TKpZY2tK/Icon-Food-2.png" },
    "焦糖布丁": { ja: "クレームブリュレ", url: "https://i.postimg.cc/rDKvFyfK/Icon-Food-3.png" },
    "焦糖爆米花": { ja: "キャラメルポップコーン", url: "https://i.postimg.cc/TKpZY2tP/Icon-Food-4.png" },
    "獸糧罐頭": { ja: "アニマル缶", url: "https://i.postimg.cc/mPt02Zmy/Icon-Food-5.pngg" },
    "扭結麵包": { ja: "プレッツェル", url: "https://i.postimg.cc/rD37d6HR/Icon-Food-6.png" },
    "蜂蜜大蒜鮭魚": { ja: "ハニーガーリックサーモン", url: "https://i.postimg.cc/qNSWtfF3/Icon-Food-7.png" },
    "烤漫畫肉": { ja: "マンガ肉焼き", url: "https://i.postimg.cc/jDmBWV1f/Icon-Food-8.png" },
    "溫熱的冰美式咖啡": { ja: "ホットアイスアメリカーノ", url: "https://i.postimg.cc/nXgNs8W7/Icon-Food-9.png" },
    "檸檬茶": { ja: "レモンティー", url: "https://i.postimg.cc/879xF8YR/Icon-Food-10.png" },
    "祕密葡萄汁": { ja: "秘密のブドウジュース", url: "https://i.postimg.cc/CRX9Zy2j/Icon-Food-11.png" },
    "太空食品": { ja: "宇宙食", url: "https://i.postimg.cc/879xF8Yb/Icon-Food-12.png" },
    "哈密瓜博孔奇尼起司": { ja: "メロンボッコンチーニ", url: "https://i.postimg.cc/jDmBWV1k/Icon-Food-13.png" },
    "一口草生菜包": { ja: "一口草-野菜包み", url: "https://i.postimg.cc/bZW4GX5m/Icon-Food-14.png" },
    "蜂蜜罐": { ja: "ハニーポット", url: "https://i.postimg.cc/BjkR8WzN/Icon-Food-15.png" },
    "海藻沙拉": { ja: "海藻サラダ", url: "https://i.postimg.cc/hX6NJFYZ/Icon-Food-16.png" },
    "南瓜濃湯": { ja: "かぼちゃ粥", url: "https://i.postimg.cc/dhpg7Mff/Icon-Food-17.png" },
    "肉桂口味糖球": { ja: "シナモン味の飴玉", url: "https://i.postimg.cc/yDt2JqGt/Icon-Food-18.png" },
    "幽靈布丁": { ja: "幽霊プリン", url: "https://i.postimg.cc/WdCxDRyx/Icon-Food-19.pngg" },
    "空氣炸豬排": { ja: "空気カツレツ", url: "https://i.postimg.cc/3kVzyMqs/Icon-Food-20.png" },
    "寶石塔": { ja: "宝石タルト", url: "https://i.postimg.cc/XZ5mdHMH/Icon-Food-21.png" },
    "石榴果實": { ja: "ガーネットの実", url: "https://i.postimg.cc/HrRFJGK1/Icon-Food-22.png" },
    "龍族糖果": { ja: "竜族キャンティ", url: "https://i.postimg.cc/t16wWS0M/Icon-Food-23.png" },
    "金糖葫蘆": { ja: "金のフルーツ飴", url: "https://i.postimg.cc/nsmgBR8S/Icon-Food-24.png" },
    "椰子松針粥": { ja: "ココナッツ松葉粥", url: "https://i.postimg.cc/kVSzK1rz/Icon-Food-25.png" },
    "麵茶": { ja: "穀物ドリンク", url: "https://i.postimg.cc/PLD9Y3Gc/Icon-Food-26.png" },
    "薄荷巧克力冰淇淋": { ja: "チョコミントアイス", url: "https://i.postimg.cc/mc9JCXx0/Icon-Food-27.png" },
    "UFC炸胡蘿蔔": { ja: "UFC ニンジンフライ", url: "https://i.postimg.cc/7Czd0svj/Icon-Food-28.png" },
    "棉花糖馬卡龍": { ja: "マシュマロマカロン", url: "https://i.postimg.cc/d7CprHPc/Icon-Food-29.png" },
    "一碗米飯": { ja: "ご飯", url: "https://i.postimg.cc/hJm6TyWB/Icon-Food-30.pn" },
    "美味維他命C": { ja: "もぐもぐビタミンC", url: "https://i.postimg.cc/hJm6TyWg/Icon-Food-31.png" },
    "松糕": { ja: "笹団子", url: "https://i.postimg.cc/Z9N2p7th/Icon-Food-32.png" },
    "酸甜維他命F": { ja: "スパビタF", url: "https://i.postimg.cc/SX93CTFk/Icon-Food-33.png" },
    "聖誕樹幹蛋糕": { ja: "ブッシュドノエル", url: "https://i.postimg.cc/7Czd0s8q/Icon-Food-34.png" },
    "杏仁金沙巧克力": { ja: "アーモンドロシェ", url: "https://i.postimg.cc/TybFg7MR/Icon-Food-35.png" },
    "年糕湯": { ja: "餅スープ", url: "https://i.postimg.cc/zLh6KtZG/Icon-Food-36.png" },
    "艾心堂綜合糖": { ja: "エーカリードロップ", url: "https://i.postimg.cc/kVSzK13G/Icon-Food-37.png" },
    "草莓切片蛋糕": { ja: "あーんイチゴケーキ", url: "https://i.postimg.cc/zLh6KtZ3/Icon-Food-38.png" },
    "ANSA太空食品": { ja: "ANSA宇宙食", url: "https://i.postimg.cc/nsmgBRbC/Icon-Food-39.png" },
    "甜甜蜂蜜罐": { ja: "ハチミツツボ", url: "https://i.postimg.cc/Z9N2p7tW/Icon-Food-40.png" },
    "龍族氣死你糖果": { ja: "逆鱗なでなでキャンディ", url: "https://i.postimg.cc/Z9N2p7tB/Icon-Food-41.png" },
    "UFC炸蔬菜": { ja: "UFC野菜フライ", url: "https://i.postimg.cc/wydPVXgq/Icon-Food-42.png" },
    "追劇焦糖爆米花": { ja: "エルフキャラメルポップコーン", url: "https://i.postimg.cc/8Fv9MKQF/Icon-Food-43.png" },
    "肉桂口味健康糖球": { ja: "シナモンの健康アメ玉", url: "https://i.postimg.cc/1nZTHGs9/Icon-Food-44.png" },
    "低糖棉花糖馬卡龍": { ja: "低糖マシュマロマカロン", url: "https://i.postimg.cc/wydPVXgv/Icon-Food-45.png" },
    "高級獸糧罐頭": { ja: "高級アニマル缶", url: "https://i.postimg.cc/MM84D7qX/Icon-Food-46.png" },
    "愛心扭結麵包": { ja: "ハートプレッツェル", url: "https://i.postimg.cc/HcCK2wdV/Icon-Food-47.png" },
    "有機檸檬茶": { ja: "オーガニックレモンティー", url: "https://i.postimg.cc/R6z8R74h/Icon-Food-48.png" },
    "兩口草生菜包": { ja: "二口草野菜包み", url: "https://i.postimg.cc/ZBhgc84v/Icon-Food-49.png" },
    "氫氣炸豬排": { ja: "水素カツレツ", url: "https://i.postimg.cc/47TM56s7/Icon-Food-50.png" },
    "椰子萬能青汁": { ja: "ココナッツ万能野菜ジュース", url: "https://i.postimg.cc/cgNjmR08/Icon-Food-51.png" },
    "軟軟焦糖布丁": { ja: "ソフトクレームフリコレ", url: "https://i.postimg.cc/sQR8cYsh/Icon-Food-52.png" },
    "白金糖葫蘆": { ja: "白銀フルーツ飴", url: "https://i.postimg.cc/1nZTHGsp/Icon-Food-53.png" },
    "皇家蜂蜜大蒜鮭魚": { ja: "ロイヤルハニーガーリックサーモン", url: "https://i.postimg.cc/R6z8R74f/Icon-Food-54.png" },
    "滾燙的冰美式咖啡": { ja: "灼熱アイスアメリカーノ", url: "https://i.postimg.cc/wydPVXgF/Icon-Food-55.png" },
    "夏威夷海藻蓋飯": { ja: "海藻ボキ", url: "https://i.postimg.cc/34H6BXYj/Icon-Food-56.png" },
    "燉南瓜": { ja: "ガほちゃシチュー", url: "https://i.postimg.cc/34H6BXYZ/Icon-Food-57.png" },
    "927穀麵茶": { ja: "927粒穀物ドリンク", url: "https://i.postimg.cc/r0LbJ1MC/Icon-Food-58.png" },
    "石榴甜茶": { ja: "ザクロフルーツパンチ", url: "https://i.postimg.cc/ygz5Pmsf/Icon-Food-59.png" },
    "一級祕密葡萄汁": { ja: "一級品秘密のフトウシュース", url: "https://i.postimg.cc/62NS0rtM/Icon-Food-60.png" },
    "寶石蛋塔": { ja: "秘宝タルト", url: "https://i.postimg.cc/ZBFQDW56/Icon-Food-61.png" },
    "一碗糯米飯": { ja: "もち米ご飯", url: "https://i.postimg.cc/Q9rPbQh4/Icon-Food-62.png" },
    "麝香甜瓜博孔奇尼起司": { ja: "マスクメロンボッコンチーニ", url: "https://i.postimg.cc/phYS1mLf/Icon-Food-63.png" },
    "惡靈布丁": { ja: "悪霊プリン", url: "https://i.postimg.cc/MMbLrnpy/Icon-Food-64.png" },
    "深黑巧克力冰淇淋": { ja: "ディープダーワチョコアイス", url: "https://i.postimg.cc/VrBhHJk9/Icon-Food-65.png" },
    "烤海賊漫畫肉": { ja: "海賊マンガ肉焼き", url: "https://i.postimg.cc/R6QYbWZL/Icon-Food-66.png" },
    "三重薄荷冰淇淋": { ja: "トリブルチョコスミントアイス", url: "https://i.postimg.cc/TLqsHK3Q/Icon-Food-67.png" },
    
    // 給 1 星角色使用的通用餐牌
    "餐牌": { ja: "メニュー", url: "https://i.postimg.cc/YGfPyvCb/My-Home-Restaurant-Menu-Icon.png" }
};

const REWARD_ICON = {
    // 🍕 食材類
    "麵粉": { ja: "小麦粉", url: "https://i.postimg.cc/Vd6QSCc7/Icon-Food-Made-Low1.png" },
    "雞蛋": { ja: "卵", url: "https://i.postimg.cc/bsJcGtjg/Icon-Food-Made-Low2.png" },
    "家禽肉": { ja: "鶏肉", url: "https://i.postimg.cc/qzRVt3dQ/Icon-Food-Made-Low3.png" },
    "水果": { ja: "果物", url: "https://i.postimg.cc/hfjWJdqy/Icon-Food-Made-Low4.png" },
    "巧克力": { ja: "チョコ", url: "https://i.postimg.cc/HVxDJyCN/Icon-Food-Made-Low5.png" },
    "糖": { ja: "砂糖", url: "https://i.postimg.cc/gnJFwZPB/Icon-Food-Made-Low6.png" },
    "牛肉": { ja: "牛肉", url: "https://i.postimg.cc/ykd4JZzp/Icon-Food-Made-Low7.png" },
    "魚": { ja: "魚", url: "https://i.postimg.cc/rKmXdrL3/Icon-Food-Made-Low8.png" },
    "堅硬的黑色果實": { ja: "黒くて硬い実", url: "https://i.postimg.cc/hfjWJdqN/Icon-Food-Made-Low9.png" },
    "各式穀物": { ja: "雑穀", url: "https://i.postimg.cc/vcBF1Vdp/Icon-Food-Made-Low10.png" },
    "蔬菜": { ja: "野菜", url: "https://i.postimg.cc/2V6RqZDp/Icon-Food-Made-Low11.png" },
    "蜂蜜": { ja: "蜜", url: "https://i.postimg.cc/GH2wBy1W/Icon-Food-Made-Low12.png" },
    "百老師萬能醬料": { ja: "万能スパイス", url: "https://i.postimg.cc/mt5x7gbm/Icon-Food-Made-Low13.png" },
    "牛奶": { ja: "牛乳", url: "https://i.postimg.cc/MvT2cQS2/Icon-Food-Made-Low14.png" },
    "米": { ja: "米", url: "https://i.postimg.cc/4mSCpxJ8/Icon-Food-Made-Low15.png" },
    "起司": { ja: "チーズ", url: "https://i.postimg.cc/9rn3yQW8/Icon-Food-Made-Low16.png" },
    "樹葉": { ja: "木の葉", url: "https://i.postimg.cc/GH50vmcg/Icon-Food-Made-Low17.png" },
    "巧克力米": { ja: "スプリンクル", url: "https://i.postimg.cc/ykbq08Vb/Icon-Food-Made-Low18.png" },

    // 🪵 素材類
    "軟棉棉的樹木": { ja: "加工しやすい木", url: "https://i.postimg.cc/YhscQCp5/Icon-Made-Low1.png" },
    "堅硬的石頭": { ja: "固い石", url: "https://i.postimg.cc/qz5f2vJf/Icon-Made-Low2.png" },
    "細膩的鐵粉": { ja: "サラサラの鉄粉", url: "https://i.postimg.cc/N5zhRjsq/Icon-Made-Low3.png" },
    "酥脆的金箔": { ja: "パリパリの金箔", url: "https://i.postimg.cc/jLFVySxY/Icon-Made-Low4.png" },
    "寶石碎片": { ja: "宝石の欠片", url: "https://i.postimg.cc/mt5x7gLG/Icon-Made-Low5.png" },
    "閃亮的玻璃": { ja: "キラキラのガラス", url: "https://i.postimg.cc/pp6NKLWR/Icon-Made-Low6.png" },
    "黏膩的黏土": { ja: "やわらか粘土", url: "https://i.postimg.cc/GH50vmLR/Icon-Made-Low7.png" },
    "濕潤的紙漿": { ja: "湿っぽい紙の原料", url: "https://i.postimg.cc/ykbq081V/Icon-Made-Low9.png" },
    "回收塑膠": { ja: "再生プラスチック", url: "https://i.postimg.cc/HVhGbkYH/Icon-Made-Low10.png" },
    "彩虹花汁": { ja: "虹の花の汁", url: "https://i.postimg.cc/6ymsCpW6/Icon-Made-Low12.png" },
    "堅硬的碎布": { ja: "ごわごわの布切れ", url: "https://i.postimg.cc/D8MV1wvw/Icon-Made-Low13.png" },
    "皮革樹葉": { ja: "レザーウッドの葉", url: "https://i.postimg.cc/jLFVySx5/Icon-Made-Low14.png" },
    "柔軟的棉花": { ja: "ふわふわ綿", url: "https://i.postimg.cc/JG2wjzrt/Icon-Made-Low15.png" },
    "槭樹樹液": { ja: "カエデの樹液", url: "https://i.postimg.cc/ZCMk65bW/Icon-Made-Low16.png" },
    "眨眼墨水": { ja: "ウィンクウィンク", url: "https://i.postimg.cc/gxXCsbjm/Icon-Made-Low18.png" },
    "睡眠眼罩": { ja: "睡眠アイマスク", url: "https://i.postimg.cc/bZD7gfrq/Icon-Made-Low20.png" },
    "銅湯匙": { ja: "銅の匙", url: "https://i.postimg.cc/mPzvjWkb/Icon-Made-Low21.png" },
    "尖銳的針": { ja: "尖った針", url: "https://i.postimg.cc/0zMTn1jk/Icon-Made-Low25.png" },
    "可彎曲金屬": { ja: "曲がったもの", url: "https://i.postimg.cc/PPRG15t0/Icon-Furn-Made-Low1.png" }
};
// ------------------------------------------
// 4. Spine 與服裝對應表
// ------------------------------------------
const SPINE_MAP = {
    "洛涅": "Rohne", "薇薇": "Vivi", "艾爾芬": "Erpin", "錫安": "xXionx", "伊弗利特": "Ifrit", "伊德": "Ed", "佩佩": "Velvet", "佩斯塔": "Festa",
    "修帕": "Shoupan", "傑德": "Jade", "優米": "Yomi", "劉美美": "Yumimi", "加薇雅": "Gabia", "卡洛特": "Kyarot", "卡蓮": "Carren", "喬菲": "Chopi",
    "基狄恩": "Kidian", "大師2號": "MaestroMK2", "大木頭": "BigWood", "奈雅": "Naia", "奶油": "Butter", "布蘭切": "Blanchet", "希拉": "Sylla", "希爾德": "Hilde",
    "希瑟圖": "Sist", "希菲爾": "Silphir", "帕特拉": "Patula", "庫洛艾": "Chloe", "康娜": "Canna", "愛麗絲": "Alice", "斑尼": "Beni", "斯皮奇": "Speaki",
    "斯諾奇": "Snorky", "柯米": "Kommy", "桃桃": "Momo", "梅森": "Maison", "梅露娜": "Meluna", "海莉": "Haley", "珀榭": "Posher", "琳": "Rim",
    "瑟琳娜": "Selline", "瑪約": "Mayo", "瑪麗": "Marie", "皮可菈": "Picora", "盧波": "Rufo", "米雪": "Mynx", "綾": "Aya", "羽伊": "Ui",
    "艾斯皮": "Espi", "艾琳娜": "Elena", "艾皮卡": "Epica", "艾舒爾": "Ashur", "艾蜜莉雅": "Amelia", "芙莉可": "Fricle", "茱蜜": "Jubee", "莉茲": "Leets",
    "莎莉": "Sari", "萊薇": "Levi", "蒂亞娜": "Diana", "謝蒂": "Shady", "貝魯": "Veroo", "貝麗塔": "Belita", "路德": "Rude", "路易": "Cuee",
    "阿萊特": "Allet", "雷吉": "Lazy", "馬爾": "Mago", "泰達": "Taida", "寧琉": "Ner", "莉絲蒂": "Risty", "R41雷內瓦": "R41_Renewa", "雷內瓦": "RenewaAwaken"
};

const COSTUME_MAP = {
    "劉美美": ["Yumimi"], "卡蓮": ["Carren"], "喬菲": ["Chopi"], "帕特拉": ["Patula"], "梅森": ["Maison"], "瑪麗": ["Marie"], "米雪": ["Mynx"], "茱蜜": ["Jubee"], "莎莉": ["Sari"], "貝魯": ["Veroo"], "路易": ["Cuee"], "阿萊特": ["Allet"], "雷吉": ["Lazy"], "泰達": ["Taida"],
    "艾舒爾": ["Ashur", "AshurSkin1"], "貝麗塔": ["Belita", "BelitaSkin1"], "斑尼": ["Beni", "BeniSkin1"], "大木頭": ["BigWood", "BigWoodSkin1"], "艾斯皮": ["Espi", "EspiSkin1"], "佩斯塔": ["Festa", "FestaSkin1"], "伊弗利特": ["Ifrit", "IfritSkin1"], "傑德": ["Jade", "JadeSkin1"], "莉茲": ["Leets", "LeetsSkin1"], "萊薇": ["Levi", "LeviSkin1"], "大師2號": ["MaestroMK2", "MaestroMK2Skin1"], "馬爾": ["Mago", "MagoSkin1"], "瑪約": ["Mayo", "MayoSkin1"], "梅露娜": ["Meluna", "MelunaSkin1"], "路德": ["Rude", "RudeSkin1"], "盧波": ["Rufo", "RufoSkin1"], "修帕": ["Shoupan", "ShoupanSkin1"], "希菲爾": ["Silphir", "SilphirSkin1"], "斯諾奇": ["Snorky", "SnorkySkin1"], "斯皮奇": ["Speaki", "SpeakiSkin1"], "佩佩": ["Velvet", "VelvetSkin1"],
    "布蘭切": ["Blanchet", "BlanchetSkin1", "BlanchetSkin2"], "奶油": ["Butter", "ButterSkin1", "ButterSkin2"], "康娜": ["Canna", "CannaSkin1", "CannaSkin2"], "伊德": ["Ed", "EdSkin1", "EdSkin2"], "艾琳娜": ["Elena", "ElenaSkin1", "ElenaSkin2"], "艾皮卡": ["Epica", "EpicaSkin1", "EpicaSkin2"], "芙莉可": ["Fricle", "FricleSkin1", "FricleSkin2"], "加薇雅": ["Gabia", "GabiaSkin1", "GabiaSkin2"], "海莉": ["Haley", "HaleySkin1", "HaleySkin2"], "希爾德": ["Hilde", "HildeSkin1", "HildeSkin2"], "基狄恩": ["Kidian", "KidianSkin1", "KidianSkin2"], "柯米": ["Kommy", "KommySkin1", "KommySkin2"], "卡洛特": ["Kyarot", "KyarotSkin1", "KyarotSkin2"], "奈雅": ["Naia", "NaiaSkin1", "NaiaSkin2"], "寧琉": ["Ner", "NerSkin1", "NerSkin2"], "皮可菈": ["Picora", "PicoraSkin1", "PicoraSkin2"], "珀榭": ["Posher", "PosherSkin1", "PosherSkin2", "PosherSkin3"], "琳": ["Rim", "RimSkin1", "RimSkin2"], "洛涅": ["Rohne", "RohneSkin1", "RohneSkin2"], "謝蒂": ["Shady", "ShadySkin1", "ShadySkin2"], "希瑟圖": ["Sist", "SistSkin1", "SistSkin2"], "希拉": ["Sylla", "SyllaSkin1", "SyllaSkin2"], "優米": ["Yomi", "YomiSkin1", "YomiSkin2"],
    "愛麗絲": ["Alice", "AliceSkin1", "AliceSkin2", "AliceSkin3"], "艾蜜莉雅": ["Amelia", "AmeliaSkin1", "AmeliaSkin2", "AmeliaSkin3"], "綾": ["Aya", "AyaSkin1", "AyaSkin2", "AyaSkin3"], "庫洛艾": ["Chloe", "ChloeSkin1", "ChloeSkin2", "ChloeSkin3"], "蒂亞娜": ["Diana", "DianaSkin1", "DianaSkin2", "DianaSkin3"], "桃桃": ["Momo", "MomoSkin1", "MomoSkin2", "MomoSkin3"], "瑟琳娜": ["Selline", "SellineSkin1", "SellineSkin2", "SellineSkin3"], "羽伊": ["Ui", "UiSkin1", "UiSkin2", "UiSkin3"], "薇薇": ["Vivi", "ViviSkin1", "ViviSkin2", "ViviSkin3"], "錫安": ["xXionx", "xXionxSkin1", "xXionxSkin2", "xXionxSkin3"],
    "艾爾芬": ["Erpin", "ErpinSkin1", "ErpinSkin2", "ErpinSkin3", "ErpinSkin4"], "莉絲蒂": ["Risty", "RistySkin1", "RistySkin2"], "雷內瓦": ["RenewaAwaken", "RenewaAwakenSkin1", "RenewaAwakenSkin2"]
};

// ------------------------------------------
// 5. 特選使者招募schedule
// ------------------------------------------

const PICKUP_SCHEDULE = [
    {
        start: "2026-06-04T17:00:00+09:00", // ISO 格式時間
        end: "2026-06-18T10:59:59+09:00",
        chars: ["莉絲蒂", "海莉", "盧波"],
        note: "現在這一期"
    },
    {
        start: "2026-06-18T17:00:00+09:00",
        end: "2026-06-25T04:00:00+09:00",
        chars: ["雷內瓦"],
        note: "牛蛙"
    },
	    {
        start: "2026-06-25T04:00:00+09:00",
        end: "2026-07-02T10:59:59+09:00",
        chars: ["雷內瓦", "琳", "錫安"],
        note: "琳、錫安坨格"
    }
];

// 🎪 遊戲內活動排程表
const EVENT_SCHEDULE = [
    {
        start: "2026-06-18T17:00:00+09:00",
        end: "2026-07-02T10:59:59+09:00",
        eventId: "Theme017" 
    },
    {
        start: "2026-06-18T17:00:00+09:00",
        end: "2026-07-16T10:59:59+09:00",
        eventId: "SelectPickPersonality" 
    }
];

// 🃏 特選卡片排程表
const CARD_SCHEDULE = [
    {
        start: "2026-06-04T17:00:00+09:00",
        end: "2026-06-18T10:59:59+09:00",
        id: "Artifact15",
        type: "Artifact"  // 類別：Artifact (神器) 或 Rune (符文)
    },
    {
        start: "2026-06-18T17:00:00+09:00",
        end: "2026-07-02T10:59:59+09:00",
        id: "Rune17",
        type: "Rune"
    }
];
console.log("LANG_DICT 內容:", LANG_DICT);
